$axure.loadCurrentPage({
  "url":"cloud.html",
  "generationDate":new Date(1411547602605.9),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0570ae91f0e046df9aa3a58922ad0712",
    "type":"Axure:Page",
    "name":"Cloud",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f8d4538796084a27a05a539f50b94a37",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":176,
              "y":660},
            "size":{
              "width":1024,
              "height":613}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"473da2782433458a9ec5e255536da782",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":176,
                  "y":660},
                "size":{
                  "width":1024,
                  "height":613}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cloud/u0.jpg"}},
{
          "id":"75ff60eacb364516a085a611d9101ba6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":176,
              "y":10},
            "size":{
              "width":1024,
              "height":616}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3396ed0ea49e4c02b8dda4e01fd99abe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":176,
                  "y":10},
                "size":{
                  "width":1024,
                  "height":616}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cloud/u2.jpg"}},
{
          "id":"8b47024454e343138a642901164b6773",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":1218,
              "y":34},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0101658f41604a918ba01a7f38153964",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":1218,
                  "y":34},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1d95a68b47ac4edbaaabe97e2da4446c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":480},
            "size":{
              "width":360,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c334bd99f6b400493cd5610de9aa76e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":360,
                  "y":480},
                "size":{
                  "width":360,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/cloud/u6.png"}},
{
          "id":"e83e77cfdd184e7f8c303f3f4d8fbadd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":367,
              "y":495},
            "size":{
              "width":309,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f43484223364a28966c3400a200d661",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":367,
                  "y":495},
                "size":{
                  "width":309,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cb1619c60a3943ec82493262fa53d017",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":848,
              "y":504},
            "size":{
              "width":209,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4fa1defe79e47a6b0cf89774886a808",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":848,
                  "y":504},
                "size":{
                  "width":209,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "f8d4538796084a27a05a539f50b94a37":{
      "scriptId":"u0"},
    "473da2782433458a9ec5e255536da782":{
      "scriptId":"u1"},
    "75ff60eacb364516a085a611d9101ba6":{
      "scriptId":"u2"},
    "3396ed0ea49e4c02b8dda4e01fd99abe":{
      "scriptId":"u3"},
    "8b47024454e343138a642901164b6773":{
      "scriptId":"u4"},
    "0101658f41604a918ba01a7f38153964":{
      "scriptId":"u5"},
    "1d95a68b47ac4edbaaabe97e2da4446c":{
      "scriptId":"u6"},
    "9c334bd99f6b400493cd5610de9aa76e":{
      "scriptId":"u7"},
    "e83e77cfdd184e7f8c303f3f4d8fbadd":{
      "scriptId":"u8"},
    "5f43484223364a28966c3400a200d661":{
      "scriptId":"u9"},
    "cb1619c60a3943ec82493262fa53d017":{
      "scriptId":"u10"},
    "c4fa1defe79e47a6b0cf89774886a808":{
      "scriptId":"u11"}}});