$axure.loadCurrentPage({
  "url":"changepwd.html",
  "generationDate":new Date(1411783646646.59),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"db18f31548fe4ec5ac4c5113947ed770",
    "type":"Axure:Page",
    "name":"ChangePwd",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b102d62786c74149b5c54998275afc80",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":210},
            "size":{
              "width":1030,
              "height":620}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c49109b5d63848f4b400c46b9b70ad49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":210},
                "size":{
                  "width":1030,
                  "height":620}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/guanzhu/u0.png"}},
{
          "id":"2174c64ebbf34bf1afd8362b668eb8e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":32},
            "size":{
              "width":800,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"368b8522c265417eae5f7149a8c6cedd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":32},
                "size":{
                  "width":800,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"2a51a51785104f6aaabe96a1026eb1e4",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":825,
              "y":70},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f0bf14bfef514bd3b866c38505134719",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1055,
              "y":70},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"3f2dcffd35e0415687afc937a5f88d7f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":6},
            "size":{
              "width":150,
              "height":116}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9fa28780b67f463d8728fabcca01d9af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":6},
                "size":{
                  "width":150,
                  "height":116}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u10.png"}},
{
          "id":"883f7b0554804ac1865b4929b57040a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":1228,
              "y":5},
            "size":{
              "width":22,
              "height":215}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb8a8b40b13243959966027bb10bd388",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":1228,
                  "y":5},
                "size":{
                  "width":22,
                  "height":215}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"13aab92b064d4e3d962048aa07585786",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1079,
              "y":11},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abd1ad8dbe4245b7add71c7c1ca666aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1079,
                  "y":11},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f6e2cc5efc164144b170aa46b35a620c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":999,
              "y":8},
            "size":{
              "width":20,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0af2d49d7f8249fc9c8101a618f718c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":999,
                  "y":8},
                "size":{
                  "width":20,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/livelist/u72.png"}},
{
          "id":"074464b47a1a47639a238181edf1597c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1029,
              "y":11},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1c927a7486346b9afc2abb5c0532c77",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1029,
                  "y":11},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"700a6addde5a4ceab06e6e77396dc473",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1177,
              "y":11},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58a14f1610ec45f88d3b3fae9543cd3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1177,
                  "y":11},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6089df72190d4f369ad7174947d4ce4e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":1116,
              "y":11},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9de35370fd5c4341ab30e87a3b5f808e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":1116,
                  "y":11},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 UserInfo",
                      "target":{
                        "targetType":"page",
                        "url":"userinfo.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f8c2461b97b4814a3b2b74c9b16a407",
          "label":"",
          "type":"treeNodeObject",
          "styleType":"treeNodeObject",
          "visible":true,
          "style":{
            "location":{
              "x":187,
              "y":260},
            "size":{
              "width":100,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6bf4aefbaa1b4e90b51d6e3b7fd141b8",
              "label":"",
              "type":"treeNodeObject",
              "styleType":"treeNodeObject",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "size":{
                  "width":80,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4586da48fa154e26abe285d7d5a02e33",
                  "label":"",
                  "isContained":true,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a4ef96089e1b4a108bdf1c31051d1dff",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0000FF,
                          "opacity":1},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"6cd1b3d5b2584f9680202080c029fc84",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":20,
                      "y":20},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ad07fe4bd0194049ab5776fb6bf4dddf",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0000FF,
                          "opacity":1},
                        "location":{
                          "x":20,
                          "y":20},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"32b469fa4af04fe09853fe5b68d53dca",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF0000FF,
                              "opacity":1},
                            "location":{
                              "x":20,
                              "y":20},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 s_MyCourse",
                              "target":{
                                "targetType":"page",
                                "url":"s_mycourse.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "buttonShapeId":"ad07fe4bd0194049ab5776fb6bf4dddf"},
{
                  "id":"b34b53de359a45f2bea0b0737992ad75",
                  "label":"",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "selected":{
}},
                    "location":{
                      "x":6,
                      "y":6},
                    "size":{
                      "width":9,
                      "height":9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e2efd9214db4497dbe2e8aad16580e67",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
}},
                        "location":{
                          "x":6,
                          "y":6},
                        "size":{
                          "width":9,
                          "height":9}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/guanzhu/u22.png",
                    "selected~":"images/guanzhu/u22_selected.png"}},
{
                  "id":"1d9edeab77a24d6ca7944a55deb59500",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":20,
                      "y":40},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a3f0e7ea813e4240b9331f0f51f33433",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0000FF,
                          "opacity":1},
                        "location":{
                          "x":20,
                          "y":40},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"65f8ea3d927445a9a3fa8d0bc458e295",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF0000FF,
                              "opacity":1},
                            "location":{
                              "x":20,
                              "y":40},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 s_MyTest",
                              "target":{
                                "targetType":"page",
                                "url":"s_mytest.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "buttonShapeId":"a3f0e7ea813e4240b9331f0f51f33433"},
{
                  "id":"711985c996ca4335abdd5f5639740277",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":20,
                      "y":60},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"aa44c86ff51e4887a20b79fbc877dcda",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0000FF,
                          "opacity":1},
                        "location":{
                          "x":20,
                          "y":60},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"46ed3653220e492bbcdf648912401af3",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF0000FF,
                              "opacity":1},
                            "location":{
                              "x":20,
                              "y":60},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 s_MyComment",
                              "target":{
                                "targetType":"page",
                                "url":"s_mycomment.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "buttonShapeId":"aa44c86ff51e4887a20b79fbc877dcda"}],
              "buttonShapeId":"4586da48fa154e26abe285d7d5a02e33"}]},
{
          "id":"d071fa5bf842480f888abf910a4d952b",
          "label":"",
          "type":"treeNodeObject",
          "styleType":"treeNodeObject",
          "visible":true,
          "style":{
            "location":{
              "x":187,
              "y":350},
            "size":{
              "width":113,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33405d09c581429689c9623a09d71bfa",
              "label":"",
              "type":"treeNodeObject",
              "styleType":"treeNodeObject",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "size":{
                  "width":80,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bd93fd20f5fa4d11bc1f9a47d2a0648c",
                  "label":"",
                  "isContained":true,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"eda2b31d9b0240ecb2f88da19138ed34",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0000FF,
                          "opacity":1},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"04513942ddae4108b691f5a1983ae612",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":20,
                      "y":20},
                    "size":{
                      "width":93,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a6eee086598548d5bacb458dbbe6a4c4",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0000FF,
                          "opacity":1},
                        "location":{
                          "x":20,
                          "y":20},
                        "size":{
                          "width":93,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"f61680f56925405cb824a8afe57861c2",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF0000FF,
                              "opacity":1},
                            "location":{
                              "x":20,
                              "y":20},
                            "size":{
                              "width":93,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 t_Machine",
                              "target":{
                                "targetType":"page",
                                "url":"t_machine.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "buttonShapeId":"a6eee086598548d5bacb458dbbe6a4c4"},
{
                  "id":"fa132d7b0159472787a38784e3ee9d9c",
                  "label":"",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "selected":{
}},
                    "location":{
                      "x":6,
                      "y":6},
                    "size":{
                      "width":9,
                      "height":9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"22e8149e4d6c4f1e916cdd109b38287b",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
}},
                        "location":{
                          "x":6,
                          "y":6},
                        "size":{
                          "width":9,
                          "height":9}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/guanzhu/u22.png",
                    "selected~":"images/guanzhu/u22_selected.png"}},
{
                  "id":"5ae83e74864447a9bd42c9ba4455f54b",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":20,
                      "y":40},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"865596f83d184238aec0d49763b04c57",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0000FF,
                          "opacity":1},
                        "location":{
                          "x":20,
                          "y":40},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"9c6f73f5e7cf4e2b8eda0f113f262b9e",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF0000FF,
                              "opacity":1},
                            "location":{
                              "x":20,
                              "y":40},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 t_MyLive",
                              "target":{
                                "targetType":"page",
                                "url":"t_mylive.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "buttonShapeId":"865596f83d184238aec0d49763b04c57"},
{
                  "id":"65c2e853852c4a1c8a4bd8141b53039e",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":20,
                      "y":60},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2353cb5aa107469b8fce0b6777abe9bf",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0000FF,
                          "opacity":1},
                        "location":{
                          "x":20,
                          "y":60},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"5f12eea9b19d46888019acc08b51b5c5",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF0000FF,
                              "opacity":1},
                            "location":{
                              "x":20,
                              "y":60},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 t_MyVod",
                              "target":{
                                "targetType":"page",
                                "url":"t_myvod.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "buttonShapeId":"2353cb5aa107469b8fce0b6777abe9bf"},
{
                  "id":"ae85439b55ab4b8a89b2f766de34548f",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":20,
                      "y":80},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9a4bfc2d6bf149e68ef47588ffc4cc8d",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0000FF,
                          "opacity":1},
                        "location":{
                          "x":20,
                          "y":80},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"b9024859df344860b2d81e0a4fc32f9d",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF0000FF,
                              "opacity":1},
                            "location":{
                              "x":20,
                              "y":80},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 t_QuestionMgr",
                              "target":{
                                "targetType":"page",
                                "url":"t_questionmgr.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "buttonShapeId":"9a4bfc2d6bf149e68ef47588ffc4cc8d"},
{
                  "id":"a826b58173e74839b35b92c1360658e4",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":20,
                      "y":100},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7cd1355dcf5045ab9cbd1e3a130d70d9",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0000FF,
                          "opacity":1},
                        "location":{
                          "x":20,
                          "y":100},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"c02abf32a79446bfb26f1ae8e9166ee0",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF0000FF,
                              "opacity":1},
                            "location":{
                              "x":20,
                              "y":100},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 t_TestMgr",
                              "target":{
                                "targetType":"page",
                                "url":"t_testmgr.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "buttonShapeId":"7cd1355dcf5045ab9cbd1e3a130d70d9"}],
              "buttonShapeId":"bd93fd20f5fa4d11bc1f9a47d2a0648c"}]},
{
          "id":"2430425b517a470b9d7526f71b0ca3ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":148,
              "y":302},
            "size":{
              "width":22,
              "height":248}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d120562fbe2541cab9aa050344d99fd5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":148,
                  "y":302},
                "size":{
                  "width":22,
                  "height":248}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"82295412d8844a4d978210e3a054ba6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1033,
              "y":224},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7a35558a946417392e3eb533d367f38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1033,
                  "y":224},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ba828735a65d464f8f540565f4cfd076",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1102,
              "y":224},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5dd65b081d44495891eb78a4ecefa072",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1102,
                  "y":224},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e006433130a146c59716ff0d56fc5a7e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":282},
            "size":{
              "width":57,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/guanzhu/u62_line.png"}},
{
          "id":"5ab91836dff54289b5a89297d4c47a7e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":224},
            "size":{
              "width":903,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/guanzhu/u63_line.png"}},
{
          "id":"a765323430444fb9b671fa69cbb7eb09",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":148,
              "y":224},
            "size":{
              "width":10,
              "height":68}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/guanzhu/u64_line.png"}},
{
          "id":"2dc049a745a24799a377433d55b329b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":840},
            "size":{
              "width":1030,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"396fee8e579b4e42999e2fac8c9aacf8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":840},
                "size":{
                  "width":1030,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u185.png"}},
{
          "id":"e29912c2b8fd43429ed63782d217c70d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":270},
            "size":{
              "width":840,
              "height":540}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"275cb5ae2cbf4d5996043a1c67d87ade",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":340,
                  "y":270},
                "size":{
                  "width":840,
                  "height":540}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/changepwd/u67.png"}},
{
          "id":"3d7e980d3ec34eebb1cdedbce3c24cf3",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":197,
              "y":480},
            "size":{
              "width":100,
              "height":154}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9212813cfb6147ad847eb94005e1c2a3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":34},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ae230375dec441249d4ac22de93cc1e1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":34},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "interactionMap":{
                "onClick":{
                  "description":"OnClick",
                  "cases":[{
                      "description":"用例 1",
                      "isNewIfGroup":false,
                      "actions":[{
                          "action":"linkWindow",
                          "description":"在 当前窗口 打开 UserInfo",
                          "target":{
                            "targetType":"page",
                            "url":"userinfo.html",
                            "includeVariables":true},
                          "linkType":"current"}]}]}},
              "tabbable":true,
              "images":{
                "normal~":"images/guanzhu/u72.png"}},
{
              "id":"dafabdbf75b94340a08a72e512d04161",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":64},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d07c8b7bcfb0484da8854ea514dd6bf9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":64},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "interactionMap":{
                "onClick":{
                  "description":"OnClick",
                  "cases":[{
                      "description":"用例 1",
                      "isNewIfGroup":false,
                      "actions":[{
                          "action":"linkWindow",
                          "description":"在 当前窗口 打开 ChangePwd",
                          "target":{
                            "targetType":"page",
                            "url":"changepwd.html",
                            "includeVariables":true},
                          "linkType":"current"}]}]}},
              "tabbable":true,
              "images":{
                "normal~":"images/guanzhu/u72.png"}},
{
              "id":"c4e53e3b929f4aeaa51a94cc02ad87ed",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":94},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d25b6522f33348ec9ee15a8dd8a098ca",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":94},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "interactionMap":{
                "onClick":{
                  "description":"OnClick",
                  "cases":[{
                      "description":"用例 1",
                      "isNewIfGroup":false,
                      "actions":[{
                          "action":"linkWindow",
                          "description":"在 当前窗口 打开 Money",
                          "target":{
                            "targetType":"page",
                            "url":"money.html",
                            "includeVariables":true},
                          "linkType":"current"}]}]}},
              "tabbable":true,
              "images":{
                "normal~":"images/guanzhu/u72.png"}},
{
              "id":"9e7b29a73c494291aa6c0187acc87328",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":124},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"49c7b379873c43c9b5e9d63daae6bd81",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":124},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "interactionMap":{
                "onClick":{
                  "description":"OnClick",
                  "cases":[{
                      "description":"用例 1",
                      "isNewIfGroup":false,
                      "actions":[{
                          "action":"linkWindow",
                          "description":"在 当前窗口 打开 Jiaoyi",
                          "target":{
                            "targetType":"page",
                            "url":"jiaoyi.html",
                            "includeVariables":true},
                          "linkType":"current"}]}]}},
              "tabbable":true,
              "images":{
                "normal~":"images/guanzhu/u78.png"}},
{
              "id":"985cba75f6794fadb99ae1d2ec25c2f8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "size":{
                  "width":100,
                  "height":34}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"430332cd19dd418a9519914b79d32a8e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "size":{
                      "width":100,
                      "height":34}},
                  "adaptiveStyles":{
}}],
              "interactionMap":{
                "onClick":{
                  "description":"OnClick",
                  "cases":[{
                      "description":"用例 1",
                      "isNewIfGroup":false,
                      "actions":[{
                          "action":"linkWindow",
                          "description":"在 当前窗口 打开 Guanzhu",
                          "target":{
                            "targetType":"page",
                            "url":"guanzhu.html",
                            "includeVariables":true},
                          "linkType":"current"}]}]}},
              "tabbable":true,
              "images":{
                "normal~":"images/guanzhu/u70.png"}}]},
{
          "id":"0241eee197f841538d35cd506a9fe1d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":152},
            "size":{
              "width":1030,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ed9fc6aff124fc2b1e4723e99717b0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":152},
                "size":{
                  "width":1030,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u12.png"}},
{
          "id":"3b01c85f70434e8a801512a27ea1ab33",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":200,
              "y":164},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ffdb4a57d3174898a97d57e09122c237",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":200,
                  "y":164},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8e4de2570d4546fcbcfdafdf45cd7294",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":253,
              "y":164},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2603cb1333104ac2a63cfd346d8a2291",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":253,
                  "y":164},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 LiveList",
                      "target":{
                        "targetType":"page",
                        "url":"livelist.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b7c039ed68d142d5925ff5e0a19b216a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":320,
              "y":164},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69419434c20e4220a7f62f68afef80a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":320,
                  "y":164},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 VodList",
                      "target":{
                        "targetType":"page",
                        "url":"vodlist.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0f0b5b6b0d854c978ef644362257ba56",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":390,
              "y":164},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb8074191e374e4b96de03219b9f26e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":390,
                  "y":164},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 SchoolList",
                      "target":{
                        "targetType":"page",
                        "url":"schoollist.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bbd295e4336842c194ad8de941c8ae47",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":453,
              "y":164},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"928061b5e2994f64bebe67f89f572af0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":453,
                  "y":164},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 TeacherList",
                      "target":{
                        "targetType":"page",
                        "url":"teacherlist.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "b102d62786c74149b5c54998275afc80":{
      "scriptId":"u0"},
    "c49109b5d63848f4b400c46b9b70ad49":{
      "scriptId":"u1"},
    "2174c64ebbf34bf1afd8362b668eb8e4":{
      "scriptId":"u2"},
    "368b8522c265417eae5f7149a8c6cedd":{
      "scriptId":"u3"},
    "2a51a51785104f6aaabe96a1026eb1e4":{
      "scriptId":"u4"},
    "f0bf14bfef514bd3b866c38505134719":{
      "scriptId":"u5"},
    "3f2dcffd35e0415687afc937a5f88d7f":{
      "scriptId":"u6"},
    "9fa28780b67f463d8728fabcca01d9af":{
      "scriptId":"u7"},
    "883f7b0554804ac1865b4929b57040a9":{
      "scriptId":"u8"},
    "cb8a8b40b13243959966027bb10bd388":{
      "scriptId":"u9"},
    "13aab92b064d4e3d962048aa07585786":{
      "scriptId":"u10"},
    "abd1ad8dbe4245b7add71c7c1ca666aa":{
      "scriptId":"u11"},
    "f6e2cc5efc164144b170aa46b35a620c":{
      "scriptId":"u12"},
    "0af2d49d7f8249fc9c8101a618f718c8":{
      "scriptId":"u13"},
    "074464b47a1a47639a238181edf1597c":{
      "scriptId":"u14"},
    "d1c927a7486346b9afc2abb5c0532c77":{
      "scriptId":"u15"},
    "700a6addde5a4ceab06e6e77396dc473":{
      "scriptId":"u16"},
    "58a14f1610ec45f88d3b3fae9543cd3f":{
      "scriptId":"u17"},
    "6089df72190d4f369ad7174947d4ce4e":{
      "scriptId":"u18"},
    "9de35370fd5c4341ab30e87a3b5f808e":{
      "scriptId":"u19"},
    "1f8c2461b97b4814a3b2b74c9b16a407":{
      "scriptId":"u20"},
    "6bf4aefbaa1b4e90b51d6e3b7fd141b8":{
      "scriptId":"u21"},
    "b34b53de359a45f2bea0b0737992ad75":{
      "scriptId":"u22"},
    "e2efd9214db4497dbe2e8aad16580e67":{
      "scriptId":"u23"},
    "4586da48fa154e26abe285d7d5a02e33":{
      "scriptId":"u24"},
    "a4ef96089e1b4a108bdf1c31051d1dff":{
      "scriptId":"u25"},
    "6cd1b3d5b2584f9680202080c029fc84":{
      "scriptId":"u26"},
    "ad07fe4bd0194049ab5776fb6bf4dddf":{
      "scriptId":"u27"},
    "32b469fa4af04fe09853fe5b68d53dca":{
      "scriptId":"u28"},
    "1d9edeab77a24d6ca7944a55deb59500":{
      "scriptId":"u29"},
    "a3f0e7ea813e4240b9331f0f51f33433":{
      "scriptId":"u30"},
    "65f8ea3d927445a9a3fa8d0bc458e295":{
      "scriptId":"u31"},
    "711985c996ca4335abdd5f5639740277":{
      "scriptId":"u32"},
    "aa44c86ff51e4887a20b79fbc877dcda":{
      "scriptId":"u33"},
    "46ed3653220e492bbcdf648912401af3":{
      "scriptId":"u34"},
    "d071fa5bf842480f888abf910a4d952b":{
      "scriptId":"u35"},
    "33405d09c581429689c9623a09d71bfa":{
      "scriptId":"u36"},
    "fa132d7b0159472787a38784e3ee9d9c":{
      "scriptId":"u37"},
    "22e8149e4d6c4f1e916cdd109b38287b":{
      "scriptId":"u38"},
    "bd93fd20f5fa4d11bc1f9a47d2a0648c":{
      "scriptId":"u39"},
    "eda2b31d9b0240ecb2f88da19138ed34":{
      "scriptId":"u40"},
    "04513942ddae4108b691f5a1983ae612":{
      "scriptId":"u41"},
    "a6eee086598548d5bacb458dbbe6a4c4":{
      "scriptId":"u42"},
    "f61680f56925405cb824a8afe57861c2":{
      "scriptId":"u43"},
    "5ae83e74864447a9bd42c9ba4455f54b":{
      "scriptId":"u44"},
    "865596f83d184238aec0d49763b04c57":{
      "scriptId":"u45"},
    "9c6f73f5e7cf4e2b8eda0f113f262b9e":{
      "scriptId":"u46"},
    "65c2e853852c4a1c8a4bd8141b53039e":{
      "scriptId":"u47"},
    "2353cb5aa107469b8fce0b6777abe9bf":{
      "scriptId":"u48"},
    "5f12eea9b19d46888019acc08b51b5c5":{
      "scriptId":"u49"},
    "ae85439b55ab4b8a89b2f766de34548f":{
      "scriptId":"u50"},
    "9a4bfc2d6bf149e68ef47588ffc4cc8d":{
      "scriptId":"u51"},
    "b9024859df344860b2d81e0a4fc32f9d":{
      "scriptId":"u52"},
    "a826b58173e74839b35b92c1360658e4":{
      "scriptId":"u53"},
    "7cd1355dcf5045ab9cbd1e3a130d70d9":{
      "scriptId":"u54"},
    "c02abf32a79446bfb26f1ae8e9166ee0":{
      "scriptId":"u55"},
    "2430425b517a470b9d7526f71b0ca3ab":{
      "scriptId":"u56"},
    "d120562fbe2541cab9aa050344d99fd5":{
      "scriptId":"u57"},
    "82295412d8844a4d978210e3a054ba6a":{
      "scriptId":"u58"},
    "c7a35558a946417392e3eb533d367f38":{
      "scriptId":"u59"},
    "ba828735a65d464f8f540565f4cfd076":{
      "scriptId":"u60"},
    "5dd65b081d44495891eb78a4ecefa072":{
      "scriptId":"u61"},
    "e006433130a146c59716ff0d56fc5a7e":{
      "scriptId":"u62"},
    "5ab91836dff54289b5a89297d4c47a7e":{
      "scriptId":"u63"},
    "a765323430444fb9b671fa69cbb7eb09":{
      "scriptId":"u64"},
    "2dc049a745a24799a377433d55b329b7":{
      "scriptId":"u65"},
    "396fee8e579b4e42999e2fac8c9aacf8":{
      "scriptId":"u66"},
    "e29912c2b8fd43429ed63782d217c70d":{
      "scriptId":"u67"},
    "275cb5ae2cbf4d5996043a1c67d87ade":{
      "scriptId":"u68"},
    "3d7e980d3ec34eebb1cdedbce3c24cf3":{
      "scriptId":"u69"},
    "985cba75f6794fadb99ae1d2ec25c2f8":{
      "scriptId":"u70"},
    "430332cd19dd418a9519914b79d32a8e":{
      "scriptId":"u71"},
    "9212813cfb6147ad847eb94005e1c2a3":{
      "scriptId":"u72"},
    "ae230375dec441249d4ac22de93cc1e1":{
      "scriptId":"u73"},
    "dafabdbf75b94340a08a72e512d04161":{
      "scriptId":"u74"},
    "d07c8b7bcfb0484da8854ea514dd6bf9":{
      "scriptId":"u75"},
    "c4e53e3b929f4aeaa51a94cc02ad87ed":{
      "scriptId":"u76"},
    "d25b6522f33348ec9ee15a8dd8a098ca":{
      "scriptId":"u77"},
    "9e7b29a73c494291aa6c0187acc87328":{
      "scriptId":"u78"},
    "49c7b379873c43c9b5e9d63daae6bd81":{
      "scriptId":"u79"},
    "0241eee197f841538d35cd506a9fe1d8":{
      "scriptId":"u80"},
    "6ed9fc6aff124fc2b1e4723e99717b0a":{
      "scriptId":"u81"},
    "3b01c85f70434e8a801512a27ea1ab33":{
      "scriptId":"u82"},
    "ffdb4a57d3174898a97d57e09122c237":{
      "scriptId":"u83"},
    "8e4de2570d4546fcbcfdafdf45cd7294":{
      "scriptId":"u84"},
    "2603cb1333104ac2a63cfd346d8a2291":{
      "scriptId":"u85"},
    "b7c039ed68d142d5925ff5e0a19b216a":{
      "scriptId":"u86"},
    "69419434c20e4220a7f62f68afef80a0":{
      "scriptId":"u87"},
    "0f0b5b6b0d854c978ef644362257ba56":{
      "scriptId":"u88"},
    "bb8074191e374e4b96de03219b9f26e5":{
      "scriptId":"u89"},
    "bbd295e4336842c194ad8de941c8ae47":{
      "scriptId":"u90"},
    "928061b5e2994f64bebe67f89f572af0":{
      "scriptId":"u91"}}});