$axure.loadCurrentPage({
  "url":"coursedetail.html",
  "generationDate":new Date(1411547600262.34),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8e3460a8ad9a4a78ba506d2f5499108e",
    "type":"Axure:Page",
    "name":"CourseDetail",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"bb7dcf8e883e44f198a83de95494b4ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":32},
            "size":{
              "width":800,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e35f2c448154a10b1a809e8f0e4cf23",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":32},
                "size":{
                  "width":800,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"413299c9589d44eb8d799605c72c636d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":825,
              "y":70},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"5f3c950828d6497eacb5276856cbe644",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1055,
              "y":70},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"9b404bc3159e4334b7dd688367ca55b0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":6},
            "size":{
              "width":150,
              "height":116}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69fd060a0c8c4a1ca5da60ba37957f0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":6},
                "size":{
                  "width":150,
                  "height":116}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u10.png"}},
{
          "id":"a30bde3c1d0b4511a5f65e24c9f12fe9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":1228,
              "y":5},
            "size":{
              "width":22,
              "height":174}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56d6224129ec4e45b11a963036ad1f43",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":1228,
                  "y":5},
                "size":{
                  "width":22,
                  "height":174}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aeab749bc1114055a0dc8b69088dc091",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":1020},
            "size":{
              "width":1030,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee71c40bf418414a989c5adff3078cce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":1020},
                "size":{
                  "width":1030,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u185.png"}},
{
          "id":"5e77a4859e994333884626c019177471",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":220},
            "size":{
              "width":310,
              "height":220}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2b88970547d4ab6959bc56211073f81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":220},
                "size":{
                  "width":310,
                  "height":220}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/coursedetail/u10.png"}},
{
          "id":"829aa75ce1f14bcfbb39d0be31266366",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":220},
            "size":{
              "width":500,
              "height":220}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5f71014a55947d69a4941e119fb14a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":220},
                "size":{
                  "width":500,
                  "height":220}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/coursedetail/u12.png"}},
{
          "id":"1aa5569ecde94677a1ceaac54bc5a1d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":460},
            "size":{
              "width":850,
              "height":550}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a47f20aa16e4a6e8bc1371b1d82609a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":460},
                "size":{
                  "width":850,
                  "height":550}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/coursedetail/u14.png"}},
{
          "id":"6dfbbb21c59c48a1b487edbc6565f70e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1050,
              "y":220},
            "size":{
              "width":160,
              "height":220}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64d36bd83ea74791a18b08d40ce1a170",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1050,
                  "y":220},
                "size":{
                  "width":160,
                  "height":220}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/coursedetail/u16.png"}},
{
          "id":"c13bf0caf857428aa6f356d836b2e00c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1050,
              "y":470},
            "size":{
              "width":160,
              "height":300}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5185a4565ec34cafb087cb4395122cea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1050,
                  "y":470},
                "size":{
                  "width":160,
                  "height":300}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/coursedetail/u18.png"}},
{
          "id":"e73c719dc5954ae895016e8b325740dd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1080,
              "y":650},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a53195d917204e24a9a82248e2fafe8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1080,
                  "y":650},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/coursedetail/u20.png"}},
{
          "id":"b70d0a9e8e734b22b41e2ea24f074ff4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1080,
              "y":480},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"091a8c5741ed43b5a5739567428b2cf4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1080,
                  "y":480},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/coursedetail/u20.png"}},
{
          "id":"c5eaa2869b064dd1b064ad0958e80311",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":460},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd37a928df6245f7b7a48ee539e947fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":460},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/coursedetail/u24.png"}},
{
          "id":"5f38ff8ec4c349129599000f7438bf4a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":198,
              "y":470},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"204759bb758e406ab6f6c71d52cf51d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":198,
                  "y":470},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5916c1fb737c415f9590b1c146e59366",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":460},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2451f1ce0e4443981af7a451c220c75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":460},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/coursedetail/u24.png"}},
{
          "id":"3a0143e458034b49ab8b451db00b08c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":278,
              "y":470},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21527c002c87435d8e2565681ed3a9ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":278,
                  "y":470},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"30e36e14c9da47baab5e58822d535679",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":341,
              "y":460},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4548dc1e6df645a4b9c97abf60efabb6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":341,
                  "y":460},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/coursedetail/u24.png"}},
{
          "id":"d9373b4fb1d64e58b51a618c113da41e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":349,
              "y":470},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03d112e1a1b14b5a94281700a6833383",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":349,
                  "y":470},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"30c73475fa2842718964056252acc8d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1050,
              "y":790},
            "size":{
              "width":160,
              "height":220}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"390a893ebba74bb285001f97eb9c9c44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1050,
                  "y":790},
                "size":{
                  "width":160,
                  "height":220}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/coursedetail/u16.png"}},
{
          "id":"3f7316edd5a043d6a5ea15872578808c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1085,
              "y":9},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0cb872936c94feea8390b4ba61fa097",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1085,
                  "y":9},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"42f320ad53f0442f973b3c345b544bb4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1005,
              "y":6},
            "size":{
              "width":20,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2e9b238a5d14dd2bcae4ddb3b151a60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1005,
                  "y":6},
                "size":{
                  "width":20,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/livelist/u72.png"}},
{
          "id":"28042d8e729c464b9f5d4ed0d82a8ebd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1035,
              "y":9},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fddf657335894c72a156f0c53c1d62e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1035,
                  "y":9},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0c9555a60b404eccad5fac8c948f5bd4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1183,
              "y":9},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35c3c91cb9bf4c6d86de6191ce4560e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1183,
                  "y":9},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"97d38f814e1e4a17afa0e13adab5f51d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":1122,
              "y":9},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae6c5b545da04cff9c21b09cb3fe17a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":1122,
                  "y":9},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 UserInfo",
                      "target":{
                        "targetType":"page",
                        "url":"userinfo.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e27b1da9f4345a5ac58468a2e7bfcdb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":152},
            "size":{
              "width":1030,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db0ee244d3324e949f8d504f65904d51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":152},
                "size":{
                  "width":1030,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u12.png"}},
{
          "id":"48bdbce6ab8e4ee28f5907fcea5b82c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":200,
              "y":164},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bca295f8f8d748e4b713940d0a31b6d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":200,
                  "y":164},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e10084a0651340d9a2fa76659bd94992",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":253,
              "y":164},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db6c874e7bf44afba34586af63b8f15f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":253,
                  "y":164},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 LiveList",
                      "target":{
                        "targetType":"page",
                        "url":"livelist.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f6654abea9044fcd8c014816e9c59ba0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":320,
              "y":164},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2bacd05293cb4241910ee7a44264fe09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":320,
                  "y":164},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 VodList",
                      "target":{
                        "targetType":"page",
                        "url":"vodlist.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"782dfedc10254138837cf9a471793a64",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":390,
              "y":164},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36051c9b6dc54211982c9f3649e8b555",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":390,
                  "y":164},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 SchoolList",
                      "target":{
                        "targetType":"page",
                        "url":"schoollist.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"790ac0a7ddf04bcf83e943e27aa4ad6d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":453,
              "y":164},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26317018a315415abab12029d02502ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":453,
                  "y":164},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 TeacherList",
                      "target":{
                        "targetType":"page",
                        "url":"teacherlist.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a32bf9b51f4a4512852af55691b3ff33",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":418,
              "y":9},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b260ef75e9de4778b0e9391e17c2bd33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":418,
                  "y":9},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"49bbbfcedcc74601a7b31ff4e700e32b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":455,
              "y":9},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1891ac01cc5b4526b3f11ae85103bf94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":455,
                  "y":9},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "bb7dcf8e883e44f198a83de95494b4ad":{
      "scriptId":"u0"},
    "1e35f2c448154a10b1a809e8f0e4cf23":{
      "scriptId":"u1"},
    "413299c9589d44eb8d799605c72c636d":{
      "scriptId":"u2"},
    "5f3c950828d6497eacb5276856cbe644":{
      "scriptId":"u3"},
    "9b404bc3159e4334b7dd688367ca55b0":{
      "scriptId":"u4"},
    "69fd060a0c8c4a1ca5da60ba37957f0d":{
      "scriptId":"u5"},
    "a30bde3c1d0b4511a5f65e24c9f12fe9":{
      "scriptId":"u6"},
    "56d6224129ec4e45b11a963036ad1f43":{
      "scriptId":"u7"},
    "aeab749bc1114055a0dc8b69088dc091":{
      "scriptId":"u8"},
    "ee71c40bf418414a989c5adff3078cce":{
      "scriptId":"u9"},
    "5e77a4859e994333884626c019177471":{
      "scriptId":"u10"},
    "b2b88970547d4ab6959bc56211073f81":{
      "scriptId":"u11"},
    "829aa75ce1f14bcfbb39d0be31266366":{
      "scriptId":"u12"},
    "b5f71014a55947d69a4941e119fb14a8":{
      "scriptId":"u13"},
    "1aa5569ecde94677a1ceaac54bc5a1d5":{
      "scriptId":"u14"},
    "2a47f20aa16e4a6e8bc1371b1d82609a":{
      "scriptId":"u15"},
    "6dfbbb21c59c48a1b487edbc6565f70e":{
      "scriptId":"u16"},
    "64d36bd83ea74791a18b08d40ce1a170":{
      "scriptId":"u17"},
    "c13bf0caf857428aa6f356d836b2e00c":{
      "scriptId":"u18"},
    "5185a4565ec34cafb087cb4395122cea":{
      "scriptId":"u19"},
    "e73c719dc5954ae895016e8b325740dd":{
      "scriptId":"u20"},
    "a53195d917204e24a9a82248e2fafe8e":{
      "scriptId":"u21"},
    "b70d0a9e8e734b22b41e2ea24f074ff4":{
      "scriptId":"u22"},
    "091a8c5741ed43b5a5739567428b2cf4":{
      "scriptId":"u23"},
    "c5eaa2869b064dd1b064ad0958e80311":{
      "scriptId":"u24"},
    "cd37a928df6245f7b7a48ee539e947fe":{
      "scriptId":"u25"},
    "5f38ff8ec4c349129599000f7438bf4a":{
      "scriptId":"u26"},
    "204759bb758e406ab6f6c71d52cf51d9":{
      "scriptId":"u27"},
    "5916c1fb737c415f9590b1c146e59366":{
      "scriptId":"u28"},
    "a2451f1ce0e4443981af7a451c220c75":{
      "scriptId":"u29"},
    "3a0143e458034b49ab8b451db00b08c7":{
      "scriptId":"u30"},
    "21527c002c87435d8e2565681ed3a9ff":{
      "scriptId":"u31"},
    "30e36e14c9da47baab5e58822d535679":{
      "scriptId":"u32"},
    "4548dc1e6df645a4b9c97abf60efabb6":{
      "scriptId":"u33"},
    "d9373b4fb1d64e58b51a618c113da41e":{
      "scriptId":"u34"},
    "03d112e1a1b14b5a94281700a6833383":{
      "scriptId":"u35"},
    "30c73475fa2842718964056252acc8d1":{
      "scriptId":"u36"},
    "390a893ebba74bb285001f97eb9c9c44":{
      "scriptId":"u37"},
    "3f7316edd5a043d6a5ea15872578808c":{
      "scriptId":"u38"},
    "f0cb872936c94feea8390b4ba61fa097":{
      "scriptId":"u39"},
    "42f320ad53f0442f973b3c345b544bb4":{
      "scriptId":"u40"},
    "b2e9b238a5d14dd2bcae4ddb3b151a60":{
      "scriptId":"u41"},
    "28042d8e729c464b9f5d4ed0d82a8ebd":{
      "scriptId":"u42"},
    "fddf657335894c72a156f0c53c1d62e2":{
      "scriptId":"u43"},
    "0c9555a60b404eccad5fac8c948f5bd4":{
      "scriptId":"u44"},
    "35c3c91cb9bf4c6d86de6191ce4560e4":{
      "scriptId":"u45"},
    "97d38f814e1e4a17afa0e13adab5f51d":{
      "scriptId":"u46"},
    "ae6c5b545da04cff9c21b09cb3fe17a3":{
      "scriptId":"u47"},
    "7e27b1da9f4345a5ac58468a2e7bfcdb":{
      "scriptId":"u48"},
    "db0ee244d3324e949f8d504f65904d51":{
      "scriptId":"u49"},
    "48bdbce6ab8e4ee28f5907fcea5b82c1":{
      "scriptId":"u50"},
    "bca295f8f8d748e4b713940d0a31b6d6":{
      "scriptId":"u51"},
    "e10084a0651340d9a2fa76659bd94992":{
      "scriptId":"u52"},
    "db6c874e7bf44afba34586af63b8f15f":{
      "scriptId":"u53"},
    "f6654abea9044fcd8c014816e9c59ba0":{
      "scriptId":"u54"},
    "2bacd05293cb4241910ee7a44264fe09":{
      "scriptId":"u55"},
    "782dfedc10254138837cf9a471793a64":{
      "scriptId":"u56"},
    "36051c9b6dc54211982c9f3649e8b555":{
      "scriptId":"u57"},
    "790ac0a7ddf04bcf83e943e27aa4ad6d":{
      "scriptId":"u58"},
    "26317018a315415abab12029d02502ce":{
      "scriptId":"u59"},
    "a32bf9b51f4a4512852af55691b3ff33":{
      "scriptId":"u60"},
    "b260ef75e9de4778b0e9391e17c2bd33":{
      "scriptId":"u61"},
    "49bbbfcedcc74601a7b31ff4e700e32b":{
      "scriptId":"u62"},
    "1891ac01cc5b4526b3f11ae85103bf94":{
      "scriptId":"u63"}}});