$axure.loadCurrentPage({
  "url":"guanzhu.html",
  "generationDate":new Date(1411547600478.48),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d7842873efe640fbab5d50d7ac33f95a",
    "type":"Axure:Page",
    "name":"Guanzhu",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5c9b100be1fe4886b49ef4a159eb70f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":210},
            "size":{
              "width":1030,
              "height":620}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"387c547962bb49adaba700f0c196d0bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":210},
                "size":{
                  "width":1030,
                  "height":620}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/guanzhu/u0.png"}},
{
          "id":"54f5d04d24a34adcbafff99029fb572b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":32},
            "size":{
              "width":800,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13f362974a2948fab20fc63fa99b20a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":32},
                "size":{
                  "width":800,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"6289e039c2cf4b03ab974d0f4bc45d2c",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":825,
              "y":70},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"9aa052237ac94ab8a4f6f5fbd2f4eda0",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1055,
              "y":70},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"885480f1b66846c4a7fe5e1bea7dd7af",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":6},
            "size":{
              "width":150,
              "height":116}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77be21b24a0147a8836a3d8d045c58c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":6},
                "size":{
                  "width":150,
                  "height":116}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u10.png"}},
{
          "id":"6646b4468c1c4d42a94b74ea5bb944d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":1228,
              "y":5},
            "size":{
              "width":22,
              "height":215}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbee2fabe98b44378b294a91321e98d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":1228,
                  "y":5},
                "size":{
                  "width":22,
                  "height":215}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c9427ded77014d55901edc110de821c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1079,
              "y":11},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"819d1cb41fb2447c964545f4e6f3d18f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1079,
                  "y":11},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5f3bf33d351248009ade2c17cec2ecd0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":999,
              "y":8},
            "size":{
              "width":20,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b99a09de7654ead88a1347cdf648f2e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":999,
                  "y":8},
                "size":{
                  "width":20,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/livelist/u72.png"}},
{
          "id":"e4dc1c6b657848b494f6b7f30253c005",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1029,
              "y":11},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa132999b7c74229aa2d027d96a76e8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1029,
                  "y":11},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"43b95c2aa70046148e4115e582c8cac9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1177,
              "y":11},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8d279f9260d4a61b1880a72f5a0366c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1177,
                  "y":11},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6c7cfecbdabc4c5cbc15627f83e41666",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":1116,
              "y":11},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d662113fa6574b3f8804b5398e094e60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":1116,
                  "y":11},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 UserInfo",
                      "target":{
                        "targetType":"page",
                        "url":"userinfo.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c48d4253d3594627a1b4abe0a848a8a1",
          "label":"",
          "type":"treeNodeObject",
          "styleType":"treeNodeObject",
          "visible":true,
          "style":{
            "location":{
              "x":187,
              "y":260},
            "size":{
              "width":100,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aff49ea5cc9d48479eff6a762a464fa1",
              "label":"",
              "type":"treeNodeObject",
              "styleType":"treeNodeObject",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "size":{
                  "width":80,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ca5e621b9e254cb59b1b5ffe8b5b6d5d",
                  "label":"",
                  "isContained":true,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"be1b90b348b342339f6b667aab049d29",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0000FF,
                          "opacity":1},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2bf90e84c5a542e6a6a123a729b188bb",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":20,
                      "y":20},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e98b75cf002b4f66a9286bad66fa9a13",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0000FF,
                          "opacity":1},
                        "location":{
                          "x":20,
                          "y":20},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"730818788ebe408e86d25899568bdfd2",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF0000FF,
                              "opacity":1},
                            "location":{
                              "x":20,
                              "y":20},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 s_MyCourse",
                              "target":{
                                "targetType":"page",
                                "url":"s_mycourse.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "buttonShapeId":"e98b75cf002b4f66a9286bad66fa9a13"},
{
                  "id":"d7e4ae0d1561487cbb5accb892a1f2b5",
                  "label":"",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "selected":{
}},
                    "location":{
                      "x":6,
                      "y":6},
                    "size":{
                      "width":9,
                      "height":9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e60366c756154cf9b673a74a0d5b083b",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
}},
                        "location":{
                          "x":6,
                          "y":6},
                        "size":{
                          "width":9,
                          "height":9}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/guanzhu/u22.png",
                    "selected~":"images/guanzhu/u22_selected.png"}},
{
                  "id":"7c47ee782fc94f1abc6aee7f298d0b69",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":20,
                      "y":40},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4a2e805dccf148909849d377349be40a",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0000FF,
                          "opacity":1},
                        "location":{
                          "x":20,
                          "y":40},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"6c3a33e3458c4be0a671ce78b978f1a8",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF0000FF,
                              "opacity":1},
                            "location":{
                              "x":20,
                              "y":40},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 s_MyTest",
                              "target":{
                                "targetType":"page",
                                "url":"s_mytest.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "buttonShapeId":"4a2e805dccf148909849d377349be40a"},
{
                  "id":"0625f8fe88564e758568c861740b37f2",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":20,
                      "y":60},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9e468fae481b4993af4849735aa927ae",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0000FF,
                          "opacity":1},
                        "location":{
                          "x":20,
                          "y":60},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"ce7e6f3e0716429291070bef8764c822",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF0000FF,
                              "opacity":1},
                            "location":{
                              "x":20,
                              "y":60},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 s_MyComment",
                              "target":{
                                "targetType":"page",
                                "url":"s_mycomment.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "buttonShapeId":"9e468fae481b4993af4849735aa927ae"}],
              "buttonShapeId":"ca5e621b9e254cb59b1b5ffe8b5b6d5d"}]},
{
          "id":"ef46fdbb1813482ea27a1f783ebb4668",
          "label":"",
          "type":"treeNodeObject",
          "styleType":"treeNodeObject",
          "visible":true,
          "style":{
            "location":{
              "x":187,
              "y":350},
            "size":{
              "width":113,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c49306d6d0db4e1687fa123d78201984",
              "label":"",
              "type":"treeNodeObject",
              "styleType":"treeNodeObject",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "size":{
                  "width":80,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b655d40a21bc4d43917dde78b4069a1b",
                  "label":"",
                  "isContained":true,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8bc6e7fc5cee47c8832b75f0353ef36a",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0000FF,
                          "opacity":1},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"be9be52bf20048d48c8ac7187df65923",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":20,
                      "y":20},
                    "size":{
                      "width":93,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cdaefd900c96468d861b3cba2a987a99",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0000FF,
                          "opacity":1},
                        "location":{
                          "x":20,
                          "y":20},
                        "size":{
                          "width":93,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"f3cec0cbbe2b4816a39944202129d853",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF0000FF,
                              "opacity":1},
                            "location":{
                              "x":20,
                              "y":20},
                            "size":{
                              "width":93,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 t_Machine",
                              "target":{
                                "targetType":"page",
                                "url":"t_machine.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "buttonShapeId":"cdaefd900c96468d861b3cba2a987a99"},
{
                  "id":"0ff83a960398474ebfff6e5c8fd90090",
                  "label":"",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "selected":{
}},
                    "location":{
                      "x":6,
                      "y":6},
                    "size":{
                      "width":9,
                      "height":9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a0fc48c5be424f8b9f6626d8c3aff862",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
}},
                        "location":{
                          "x":6,
                          "y":6},
                        "size":{
                          "width":9,
                          "height":9}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/guanzhu/u22.png",
                    "selected~":"images/guanzhu/u22_selected.png"}},
{
                  "id":"fd5c893c3da5487c8252af7ae038a7d2",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":20,
                      "y":40},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4052b2730a8c481daaa562f0b59b856a",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0000FF,
                          "opacity":1},
                        "location":{
                          "x":20,
                          "y":40},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"ca359b77b6294a2a8dc631e198f92bc6",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF0000FF,
                              "opacity":1},
                            "location":{
                              "x":20,
                              "y":40},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 t_MyLive",
                              "target":{
                                "targetType":"page",
                                "url":"t_mylive.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "buttonShapeId":"4052b2730a8c481daaa562f0b59b856a"},
{
                  "id":"5bec8ba4032b474197b307c082d1318b",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":20,
                      "y":60},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4bf240d810294ff39b636e37554f9fe9",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0000FF,
                          "opacity":1},
                        "location":{
                          "x":20,
                          "y":60},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"395c7d2a83a94674876b4f3d537eaffc",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF0000FF,
                              "opacity":1},
                            "location":{
                              "x":20,
                              "y":60},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 t_MyVod",
                              "target":{
                                "targetType":"page",
                                "url":"t_myvod.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "buttonShapeId":"4bf240d810294ff39b636e37554f9fe9"},
{
                  "id":"a37bd39d2721476fbb65c4b5a048b2f2",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":20,
                      "y":80},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4b861c83e4634ed3b3c1fe3338b3610b",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0000FF,
                          "opacity":1},
                        "location":{
                          "x":20,
                          "y":80},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"bd1c436d9ccc4a3cb3ef94bcf99f3cdf",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF0000FF,
                              "opacity":1},
                            "location":{
                              "x":20,
                              "y":80},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 t_QuestionMgr",
                              "target":{
                                "targetType":"page",
                                "url":"t_questionmgr.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "buttonShapeId":"4b861c83e4634ed3b3c1fe3338b3610b"},
{
                  "id":"0873c51225954a8e91ac2af9ea0e769e",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":20,
                      "y":100},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8f156fa1602043fab9e129504a1b088f",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0000FF,
                          "opacity":1},
                        "location":{
                          "x":20,
                          "y":100},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"6c2d7cd6c5d34dfbb58f77c15a45aad3",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF0000FF,
                              "opacity":1},
                            "location":{
                              "x":20,
                              "y":100},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 t_TestMgr",
                              "target":{
                                "targetType":"page",
                                "url":"t_testmgr.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "buttonShapeId":"8f156fa1602043fab9e129504a1b088f"}],
              "buttonShapeId":"b655d40a21bc4d43917dde78b4069a1b"}]},
{
          "id":"0c46d55483364a19a881e4e1bed3b096",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":148,
              "y":302},
            "size":{
              "width":22,
              "height":248}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de032548ff194d4a8ef834efdb84cd59",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":148,
                  "y":302},
                "size":{
                  "width":22,
                  "height":248}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0c006436f41a4ad2a835a9bd78cd701e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1033,
              "y":224},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"874006238df9470590692643a8b0b464",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1033,
                  "y":224},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8354dc4bd0364cd29c9028b2f5ec8c65",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1102,
              "y":224},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc2a4fad96ec4b22b8a681a71bacfb3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1102,
                  "y":224},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2b269ba33e8f439e9c4d5f43c7db7307",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":282},
            "size":{
              "width":57,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/guanzhu/u62_line.png"}},
{
          "id":"140ec9bf3c914bb4ae8eef2961a58c18",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":224},
            "size":{
              "width":903,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/guanzhu/u63_line.png"}},
{
          "id":"a8d328eeddf6447ca19939dd845b7637",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":148,
              "y":224},
            "size":{
              "width":10,
              "height":68}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/guanzhu/u64_line.png"}},
{
          "id":"f648b7d05dee4c9da5d66f160669706b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":840},
            "size":{
              "width":1030,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27e3bb3a07534d30926cd76b9061e413",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":840},
                "size":{
                  "width":1030,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u185.png"}},
{
          "id":"a47f1d26dca64db48a48227d2746bdd0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":260},
            "size":{
              "width":839,
              "height":550}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6ecec23dbf0464e8e2e0d02585fc0ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":330,
                  "y":260},
                "size":{
                  "width":839,
                  "height":550}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/guanzhu/u67.png"}},
{
          "id":"c1c383c97fa2485ab8281ecd050cb1bf",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":197,
              "y":480},
            "size":{
              "width":100,
              "height":154}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63a1b474b38442c1aa2875a3f24fa895",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":34},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0f4aecda2ba54fb68027db1b592942b6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":34},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "interactionMap":{
                "onClick":{
                  "description":"OnClick",
                  "cases":[{
                      "description":"用例 1",
                      "isNewIfGroup":false,
                      "actions":[{
                          "action":"linkWindow",
                          "description":"在 当前窗口 打开 UserInfo",
                          "target":{
                            "targetType":"page",
                            "url":"userinfo.html",
                            "includeVariables":true},
                          "linkType":"current"}]}]}},
              "tabbable":true,
              "images":{
                "normal~":"images/guanzhu/u72.png"}},
{
              "id":"0b34a89f82884dae8e796d17b361bd43",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":64},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"441ed67a241548c78c4d5069eb8ea100",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":64},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "interactionMap":{
                "onClick":{
                  "description":"OnClick",
                  "cases":[{
                      "description":"用例 1",
                      "isNewIfGroup":false,
                      "actions":[{
                          "action":"linkWindow",
                          "description":"在 当前窗口 打开 ChangePwd",
                          "target":{
                            "targetType":"page",
                            "url":"changepwd.html",
                            "includeVariables":true},
                          "linkType":"current"}]}]}},
              "tabbable":true,
              "images":{
                "normal~":"images/guanzhu/u72.png"}},
{
              "id":"c06f0f7b22154aaca3f10968239cc62a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":94},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"29b5b5f953e14ab4aedb63268901dcd7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":94},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "interactionMap":{
                "onClick":{
                  "description":"OnClick",
                  "cases":[{
                      "description":"用例 1",
                      "isNewIfGroup":false,
                      "actions":[{
                          "action":"linkWindow",
                          "description":"在 当前窗口 打开 Money",
                          "target":{
                            "targetType":"page",
                            "url":"money.html",
                            "includeVariables":true},
                          "linkType":"current"}]}]}},
              "tabbable":true,
              "images":{
                "normal~":"images/guanzhu/u72.png"}},
{
              "id":"e4d541d6b2e7417fa5f1e7538807a75b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":124},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"66507657291e4f6d977415d3bcbd2f6f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":124},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "interactionMap":{
                "onClick":{
                  "description":"OnClick",
                  "cases":[{
                      "description":"用例 1",
                      "isNewIfGroup":false,
                      "actions":[{
                          "action":"linkWindow",
                          "description":"在 当前窗口 打开 Jiaoyi",
                          "target":{
                            "targetType":"page",
                            "url":"jiaoyi.html",
                            "includeVariables":true},
                          "linkType":"current"}]}]}},
              "tabbable":true,
              "images":{
                "normal~":"images/guanzhu/u78.png"}},
{
              "id":"b29bd7c3d2b2491ea65e074033f5f948",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "size":{
                  "width":100,
                  "height":34}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"40626e102e0d41ec9613974c2516a10f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "size":{
                      "width":100,
                      "height":34}},
                  "adaptiveStyles":{
}}],
              "interactionMap":{
                "onClick":{
                  "description":"OnClick",
                  "cases":[{
                      "description":"用例 1",
                      "isNewIfGroup":false,
                      "actions":[{
                          "action":"linkWindow",
                          "description":"在 当前窗口 打开 Guanzhu",
                          "target":{
                            "targetType":"page",
                            "url":"guanzhu.html",
                            "includeVariables":true},
                          "linkType":"current"}]}]}},
              "tabbable":true,
              "images":{
                "normal~":"images/guanzhu/u70.png"}}]},
{
          "id":"c55806cc5dd44c529169a9802652b597",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":152},
            "size":{
              "width":1030,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"610bb8b219c34ca6b4e6cd2063a0ec6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":152},
                "size":{
                  "width":1030,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u12.png"}},
{
          "id":"89b335b6e5a44243b2c520cf638052a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":200,
              "y":164},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7594281731ce49fc917cab23704a4a72",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":200,
                  "y":164},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"161d3556bf9f492597a3ea60779ac920",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":253,
              "y":164},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f7a25a6e66e4f05af24dd726eac5d1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":253,
                  "y":164},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 LiveList",
                      "target":{
                        "targetType":"page",
                        "url":"livelist.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b22698c5e1d24037b2f00fe8e2310f0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":320,
              "y":164},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"183755b0b49e444587fc21334f85ee15",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":320,
                  "y":164},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 VodList",
                      "target":{
                        "targetType":"page",
                        "url":"vodlist.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3854c5889d8d426aae1fab7214b3b22e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":390,
              "y":164},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51b03a2579bd4a54a067fd07819266b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":390,
                  "y":164},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 SchoolList",
                      "target":{
                        "targetType":"page",
                        "url":"schoollist.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c556d7c9860d428f9be3e85a607b6980",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":453,
              "y":164},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d9ea0a903634a3289eb6e90f7ab783d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":453,
                  "y":164},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 TeacherList",
                      "target":{
                        "targetType":"page",
                        "url":"teacherlist.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "5c9b100be1fe4886b49ef4a159eb70f1":{
      "scriptId":"u0"},
    "387c547962bb49adaba700f0c196d0bb":{
      "scriptId":"u1"},
    "54f5d04d24a34adcbafff99029fb572b":{
      "scriptId":"u2"},
    "13f362974a2948fab20fc63fa99b20a1":{
      "scriptId":"u3"},
    "6289e039c2cf4b03ab974d0f4bc45d2c":{
      "scriptId":"u4"},
    "9aa052237ac94ab8a4f6f5fbd2f4eda0":{
      "scriptId":"u5"},
    "885480f1b66846c4a7fe5e1bea7dd7af":{
      "scriptId":"u6"},
    "77be21b24a0147a8836a3d8d045c58c5":{
      "scriptId":"u7"},
    "6646b4468c1c4d42a94b74ea5bb944d6":{
      "scriptId":"u8"},
    "bbee2fabe98b44378b294a91321e98d7":{
      "scriptId":"u9"},
    "c9427ded77014d55901edc110de821c4":{
      "scriptId":"u10"},
    "819d1cb41fb2447c964545f4e6f3d18f":{
      "scriptId":"u11"},
    "5f3bf33d351248009ade2c17cec2ecd0":{
      "scriptId":"u12"},
    "9b99a09de7654ead88a1347cdf648f2e":{
      "scriptId":"u13"},
    "e4dc1c6b657848b494f6b7f30253c005":{
      "scriptId":"u14"},
    "aa132999b7c74229aa2d027d96a76e8c":{
      "scriptId":"u15"},
    "43b95c2aa70046148e4115e582c8cac9":{
      "scriptId":"u16"},
    "f8d279f9260d4a61b1880a72f5a0366c":{
      "scriptId":"u17"},
    "6c7cfecbdabc4c5cbc15627f83e41666":{
      "scriptId":"u18"},
    "d662113fa6574b3f8804b5398e094e60":{
      "scriptId":"u19"},
    "c48d4253d3594627a1b4abe0a848a8a1":{
      "scriptId":"u20"},
    "aff49ea5cc9d48479eff6a762a464fa1":{
      "scriptId":"u21"},
    "d7e4ae0d1561487cbb5accb892a1f2b5":{
      "scriptId":"u22"},
    "e60366c756154cf9b673a74a0d5b083b":{
      "scriptId":"u23"},
    "ca5e621b9e254cb59b1b5ffe8b5b6d5d":{
      "scriptId":"u24"},
    "be1b90b348b342339f6b667aab049d29":{
      "scriptId":"u25"},
    "2bf90e84c5a542e6a6a123a729b188bb":{
      "scriptId":"u26"},
    "e98b75cf002b4f66a9286bad66fa9a13":{
      "scriptId":"u27"},
    "730818788ebe408e86d25899568bdfd2":{
      "scriptId":"u28"},
    "7c47ee782fc94f1abc6aee7f298d0b69":{
      "scriptId":"u29"},
    "4a2e805dccf148909849d377349be40a":{
      "scriptId":"u30"},
    "6c3a33e3458c4be0a671ce78b978f1a8":{
      "scriptId":"u31"},
    "0625f8fe88564e758568c861740b37f2":{
      "scriptId":"u32"},
    "9e468fae481b4993af4849735aa927ae":{
      "scriptId":"u33"},
    "ce7e6f3e0716429291070bef8764c822":{
      "scriptId":"u34"},
    "ef46fdbb1813482ea27a1f783ebb4668":{
      "scriptId":"u35"},
    "c49306d6d0db4e1687fa123d78201984":{
      "scriptId":"u36"},
    "0ff83a960398474ebfff6e5c8fd90090":{
      "scriptId":"u37"},
    "a0fc48c5be424f8b9f6626d8c3aff862":{
      "scriptId":"u38"},
    "b655d40a21bc4d43917dde78b4069a1b":{
      "scriptId":"u39"},
    "8bc6e7fc5cee47c8832b75f0353ef36a":{
      "scriptId":"u40"},
    "be9be52bf20048d48c8ac7187df65923":{
      "scriptId":"u41"},
    "cdaefd900c96468d861b3cba2a987a99":{
      "scriptId":"u42"},
    "f3cec0cbbe2b4816a39944202129d853":{
      "scriptId":"u43"},
    "fd5c893c3da5487c8252af7ae038a7d2":{
      "scriptId":"u44"},
    "4052b2730a8c481daaa562f0b59b856a":{
      "scriptId":"u45"},
    "ca359b77b6294a2a8dc631e198f92bc6":{
      "scriptId":"u46"},
    "5bec8ba4032b474197b307c082d1318b":{
      "scriptId":"u47"},
    "4bf240d810294ff39b636e37554f9fe9":{
      "scriptId":"u48"},
    "395c7d2a83a94674876b4f3d537eaffc":{
      "scriptId":"u49"},
    "a37bd39d2721476fbb65c4b5a048b2f2":{
      "scriptId":"u50"},
    "4b861c83e4634ed3b3c1fe3338b3610b":{
      "scriptId":"u51"},
    "bd1c436d9ccc4a3cb3ef94bcf99f3cdf":{
      "scriptId":"u52"},
    "0873c51225954a8e91ac2af9ea0e769e":{
      "scriptId":"u53"},
    "8f156fa1602043fab9e129504a1b088f":{
      "scriptId":"u54"},
    "6c2d7cd6c5d34dfbb58f77c15a45aad3":{
      "scriptId":"u55"},
    "0c46d55483364a19a881e4e1bed3b096":{
      "scriptId":"u56"},
    "de032548ff194d4a8ef834efdb84cd59":{
      "scriptId":"u57"},
    "0c006436f41a4ad2a835a9bd78cd701e":{
      "scriptId":"u58"},
    "874006238df9470590692643a8b0b464":{
      "scriptId":"u59"},
    "8354dc4bd0364cd29c9028b2f5ec8c65":{
      "scriptId":"u60"},
    "bc2a4fad96ec4b22b8a681a71bacfb3d":{
      "scriptId":"u61"},
    "2b269ba33e8f439e9c4d5f43c7db7307":{
      "scriptId":"u62"},
    "140ec9bf3c914bb4ae8eef2961a58c18":{
      "scriptId":"u63"},
    "a8d328eeddf6447ca19939dd845b7637":{
      "scriptId":"u64"},
    "f648b7d05dee4c9da5d66f160669706b":{
      "scriptId":"u65"},
    "27e3bb3a07534d30926cd76b9061e413":{
      "scriptId":"u66"},
    "a47f1d26dca64db48a48227d2746bdd0":{
      "scriptId":"u67"},
    "c6ecec23dbf0464e8e2e0d02585fc0ec":{
      "scriptId":"u68"},
    "c1c383c97fa2485ab8281ecd050cb1bf":{
      "scriptId":"u69"},
    "b29bd7c3d2b2491ea65e074033f5f948":{
      "scriptId":"u70"},
    "40626e102e0d41ec9613974c2516a10f":{
      "scriptId":"u71"},
    "63a1b474b38442c1aa2875a3f24fa895":{
      "scriptId":"u72"},
    "0f4aecda2ba54fb68027db1b592942b6":{
      "scriptId":"u73"},
    "0b34a89f82884dae8e796d17b361bd43":{
      "scriptId":"u74"},
    "441ed67a241548c78c4d5069eb8ea100":{
      "scriptId":"u75"},
    "c06f0f7b22154aaca3f10968239cc62a":{
      "scriptId":"u76"},
    "29b5b5f953e14ab4aedb63268901dcd7":{
      "scriptId":"u77"},
    "e4d541d6b2e7417fa5f1e7538807a75b":{
      "scriptId":"u78"},
    "66507657291e4f6d977415d3bcbd2f6f":{
      "scriptId":"u79"},
    "c55806cc5dd44c529169a9802652b597":{
      "scriptId":"u80"},
    "610bb8b219c34ca6b4e6cd2063a0ec6b":{
      "scriptId":"u81"},
    "89b335b6e5a44243b2c520cf638052a8":{
      "scriptId":"u82"},
    "7594281731ce49fc917cab23704a4a72":{
      "scriptId":"u83"},
    "161d3556bf9f492597a3ea60779ac920":{
      "scriptId":"u84"},
    "6f7a25a6e66e4f05af24dd726eac5d1d":{
      "scriptId":"u85"},
    "b22698c5e1d24037b2f00fe8e2310f0f":{
      "scriptId":"u86"},
    "183755b0b49e444587fc21334f85ee15":{
      "scriptId":"u87"},
    "3854c5889d8d426aae1fab7214b3b22e":{
      "scriptId":"u88"},
    "51b03a2579bd4a54a067fd07819266b4":{
      "scriptId":"u89"},
    "c556d7c9860d428f9be3e85a607b6980":{
      "scriptId":"u90"},
    "9d9ea0a903634a3289eb6e90f7ab783d":{
      "scriptId":"u91"}}});