$axure.loadCurrentPage({
  "url":"livelist.html",
  "generationDate":new Date(1411547599870.08),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3385b61451ef4fc79d21d059526c6eea",
    "type":"Axure:Page",
    "name":"LiveList",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"50ec119ed80b45c6b5bb53681cba8689",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1030,
              "y":537},
            "size":{
              "width":180,
              "height":290}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11ea8be376e44af4afff91bef6ca946c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1030,
                  "y":537},
                "size":{
                  "width":180,
                  "height":290}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/livelist/u0.png"}},
{
          "id":"ec87fe7360c947199e4ecaef06230938",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":410},
            "size":{
              "width":830,
              "height":810}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99a3378e4b9f47ea98b3fce8e44f4874",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":410},
                "size":{
                  "width":830,
                  "height":810}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/livelist/u2.png"}},
{
          "id":"39021420f73549f0b296745ca3e5e3df",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":790},
            "size":{
              "width":750,
              "height":200}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"600c0e66a9944f37b5af4d251a5982f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":790},
                "size":{
                  "width":750,
                  "height":200}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/livelist/u4.png"}},
{
          "id":"43ac58d164be49f999032ea50798f809",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":210},
            "size":{
              "width":830,
              "height":140}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb4bd5bbec534efa8580af623fd44685",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":210},
                "size":{
                  "width":830,
                  "height":140}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/livelist/u6.png"}},
{
          "id":"57cb11226a4545ef8b11c4dbca8317a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1030,
              "y":210},
            "size":{
              "width":180,
              "height":290}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c550a613d8c24f58b714078dac192577",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1030,
                  "y":210},
                "size":{
                  "width":180,
                  "height":290}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/livelist/u0.png"}},
{
          "id":"56f8b8b055db4323a33df79c02a01ed8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1040,
              "y":220},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"056b80ccd12c477e99e0c8afa0fdfc05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1040,
                  "y":220},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1e4586e05d074ddca13f8f20addef76d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1054,
              "y":260},
            "size":{
              "width":136,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"243c3972f15f4808865f07a66e176d9c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1054,
                  "y":260},
                "size":{
                  "width":136,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/livelist/u12.png"}},
{
          "id":"95b1492439bb448d9505e581ab65a0c5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1054,
              "y":390},
            "size":{
              "width":136,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29b9d6e8109f45ff8945e5b2a3a97c15",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1054,
                  "y":390},
                "size":{
                  "width":136,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/livelist/u12.png"}},
{
          "id":"f9c3c945c0d44c0684bc20de0996c2fc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1054,
              "y":599},
            "size":{
              "width":136,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae8e4202049b413bb2a02289034d1d91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1054,
                  "y":599},
                "size":{
                  "width":136,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/livelist/u12.png"}},
{
          "id":"1884da2ed9f6487b916370d182ddbb0e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1052,
              "y":716},
            "size":{
              "width":136,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"628e69b07a5f4ffbbf9ff27bf28277ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1052,
                  "y":716},
                "size":{
                  "width":136,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/livelist/u12.png"}},
{
          "id":"d32505d853934107a1615a0f99f8546b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":224},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b747d7a663ff44d191d8b4eebd05b86c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":224},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"991dae78e8614b60a6754008806a66d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":277,
              "y":224},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1322a61c883c46639df3f237bea29896",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":277,
                  "y":224},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"613597b2a85841e5bb957634dd63652c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":347,
              "y":224},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbb988f47ca44fc6a40f19a092480428",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":347,
                  "y":224},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"094df6fb7f9a4f43aafb5b21264c2d86",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":224},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd5eb03c028d4fb9af7183b72c8bbcb3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":224},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9921ad67b4f742d98cf9faa79e543206",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":370},
            "size":{
              "width":830,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2bd59441e3943ee94cfc912dd413d0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":370},
                "size":{
                  "width":830,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/livelist/u28.png"}},
{
          "id":"11ad6c791ab845a58daf0ca489fb57f2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":450},
            "size":{
              "width":170,
              "height":140}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9195d58e61c14999b650bd3041d28df3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":450},
                "size":{
                  "width":170,
                  "height":140}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/livelist/u30.png"}},
{
          "id":"8c211229eb0c44628f66b2519b39b1f2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":490,
              "y":620},
            "size":{
              "width":170,
              "height":140}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad4e9aa45dad4fe98fa057909e7d5084",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":490,
                  "y":620},
                "size":{
                  "width":170,
                  "height":140}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/livelist/u30.png"}},
{
          "id":"d2dda79914c7456ab9d472d4b901dcc1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":780,
              "y":450},
            "size":{
              "width":170,
              "height":140}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9795bb6009684daa9fd4742c58a7ee7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":780,
                  "y":450},
                "size":{
                  "width":170,
                  "height":140}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/livelist/u30.png"}},
{
          "id":"c91b1226a3d04333b5171e9fe3626562",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":464,
              "y":504},
            "size":{
              "width":222,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eeb238ede0da45aba870e68fbdd89d5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":464,
                  "y":504},
                "size":{
                  "width":222,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c4d3ea99d7954036b9e39c30f7cf2ff5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":242,
              "y":805},
            "size":{
              "width":730,
              "height":170}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"145474d0195b44cd89a2d0e3690d6b32",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":242,
                  "y":805},
                "size":{
                  "width":730,
                  "height":170}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/livelist/u38.jpg"}},
{
          "id":"35320f289585448c91bc10f254e76d44",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":1000},
            "size":{
              "width":750,
              "height":200}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fb3e80851b14156b3ea487ad88fd02c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":1000},
                "size":{
                  "width":750,
                  "height":200}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/livelist/u4.png"}},
{
          "id":"c9942c3a6b46468d8fea00c57fdeaad1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":235,
              "y":1007},
            "size":{
              "width":737,
              "height":183}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"780be42ff92f43a284ba860558a05f2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":235,
                  "y":1007},
                "size":{
                  "width":737,
                  "height":183}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/livelist/u42.jpg"}},
{
          "id":"643342d1727747a1b476c485432b6225",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":820},
            "size":{
              "width":20,
              "height":113}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c26d0aeb342a4b859891298a70deb700",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":820},
                "size":{
                  "width":20,
                  "height":113}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b005b0b868ad4fcfb56f1e12c5bbeae2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":1030},
            "size":{
              "width":20,
              "height":113}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"179d11c450474c09970143f4a8d7a1a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":1030},
                "size":{
                  "width":20,
                  "height":113}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1e831509f3b243b4b1d84e5a409e43da",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":174,
              "y":1237},
            "size":{
              "width":1030,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01e547f6e2bc46ac8469ffb3e3602c2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":174,
                  "y":1237},
                "size":{
                  "width":1030,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u185.png"}},
{
          "id":"52db46fd86b54f5b8de5fda4fb75bd29",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":98,
              "y":276},
            "size":{
              "width":22,
              "height":234}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"842e38a6b98240e39ebc46e81941ff0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":98,
                  "y":276},
                "size":{
                  "width":22,
                  "height":234}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"871ee153cda24f888dd41ece0cd179e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":32},
            "size":{
              "width":800,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"323eaf330e864bd2820cdb7ec0f560d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":32},
                "size":{
                  "width":800,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"02fc1b44730d4c539ecff87474ea2d60",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":825,
              "y":70},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"e515d56e60774b299ec1ef72176d2d49",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1055,
              "y":70},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a270295c57b64cfcb2e233b463d5838b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":6},
            "size":{
              "width":150,
              "height":116}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f041507fd5b483b8b10adcafa9a7423",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":6},
                "size":{
                  "width":150,
                  "height":116}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u10.png"}},
{
          "id":"220db36c24f841418b1d9f5332d122ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":1228,
              "y":5},
            "size":{
              "width":22,
              "height":174}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9a454add4234d95b1c64c906f53e064",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":1228,
                  "y":5},
                "size":{
                  "width":22,
                  "height":174}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bb6fab3a1b18462f9cd24eb7022ae9e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1030,
              "y":850},
            "size":{
              "width":180,
              "height":370}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da02a420d38448c8806666545141294e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1030,
                  "y":850},
                "size":{
                  "width":180,
                  "height":370}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/livelist/u60.png"}},
{
          "id":"31e795b3914a4ce78731c97c91dd8bc9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1053,
              "y":950},
            "size":{
              "width":136,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b75f652dfe34a4b9abe668d4120c105",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1053,
                  "y":950},
                "size":{
                  "width":136,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/livelist/u12.png"}},
{
          "id":"daff5fd3bb514706891b87704f64a490",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1051,
              "y":1100},
            "size":{
              "width":136,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"419142a0d65d46cca7f20eaf15312197",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1051,
                  "y":1100},
                "size":{
                  "width":136,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/livelist/u12.png"}},
{
          "id":"02244269039a4d948f4fea323e7c01e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1051,
              "y":874},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4938f412c580461aad6a2abb2ca8a800",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1051,
                  "y":874},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"06b1cee48ba847089c03ba9132b7fa1f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":1220,
              "y":882},
            "size":{
              "width":20,
              "height":248}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfe18b3862724d6b927a6cbbfee3fa5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":1220,
                  "y":882},
                "size":{
                  "width":20,
                  "height":248}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"43658626e3354ad3b1e1642eaabcb30d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1085,
              "y":9},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8cf9a54fbd4c406e9b82f8050314b370",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1085,
                  "y":9},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b6a4beca02f04830bbe15419034bdfff",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1005,
              "y":6},
            "size":{
              "width":20,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc63c420a43642e2a89a6a7fedde030c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1005,
                  "y":6},
                "size":{
                  "width":20,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/livelist/u72.png"}},
{
          "id":"d36ad0521dc14241a14797313be91c18",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1035,
              "y":9},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c97e16d2ea2b4144a9ba2ae074ea20c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1035,
                  "y":9},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"36f8dae8270a494e9dd9e4c7ea89307f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1183,
              "y":9},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7abfcbc344d64118a009010de8a49a26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1183,
                  "y":9},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0cdcb83d188148828d807374df2d63b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":1122,
              "y":9},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"059f246b1ffb4dd08f8a56edef6b13b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":1122,
                  "y":9},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 UserInfo",
                      "target":{
                        "targetType":"page",
                        "url":"userinfo.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b9161238dea94f649e2cb8b27ae9f53c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":152},
            "size":{
              "width":1030,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76f68c0b4a0146a388b13e713439f2fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":152},
                "size":{
                  "width":1030,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u12.png"}},
{
          "id":"085ed80f9ae845b8b29b9f590b78dbf5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":200,
              "y":164},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff47921e205a454898f7955d940fa7ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":200,
                  "y":164},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"39c04b23dfdf462990652c5861233666",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":253,
              "y":164},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1870a4da94d04c589272f2c1a75a65d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":253,
                  "y":164},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 LiveList",
                      "target":{
                        "targetType":"page",
                        "url":"livelist.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"76ae9e357d6c46c2b4705553364fc11e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":320,
              "y":164},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff23902fbd954f8aba5d9b0fa0aee833",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":320,
                  "y":164},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 VodList",
                      "target":{
                        "targetType":"page",
                        "url":"vodlist.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2045b1d50b214312a81428f6690b6ad0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":390,
              "y":164},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e554eadb14024631bf8a80836bef2b98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":390,
                  "y":164},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 SchoolList",
                      "target":{
                        "targetType":"page",
                        "url":"schoollist.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f199aa9a820347069f5076b487ce6d56",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":453,
              "y":164},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9649b5acda6b48f895c600ca47abc23d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":453,
                  "y":164},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 TeacherList",
                      "target":{
                        "targetType":"page",
                        "url":"teacherlist.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"404aa6df20424c8480aa97b3f1844393",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":418,
              "y":9},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8c2ff1af87b4c0697748c97e05e614e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":418,
                  "y":9},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b4733d7a5a08471880053993f0d198df",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":455,
              "y":9},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31d97334f5e7470ea6357fc43a7e7583",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":455,
                  "y":9},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"539b0161ae0344ea8f3879913ab1c547",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1040,
              "y":560},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e40a272d0534f22a0c87f84c919a3bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1040,
                  "y":560},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "50ec119ed80b45c6b5bb53681cba8689":{
      "scriptId":"u0"},
    "11ea8be376e44af4afff91bef6ca946c":{
      "scriptId":"u1"},
    "ec87fe7360c947199e4ecaef06230938":{
      "scriptId":"u2"},
    "99a3378e4b9f47ea98b3fce8e44f4874":{
      "scriptId":"u3"},
    "39021420f73549f0b296745ca3e5e3df":{
      "scriptId":"u4"},
    "600c0e66a9944f37b5af4d251a5982f9":{
      "scriptId":"u5"},
    "43ac58d164be49f999032ea50798f809":{
      "scriptId":"u6"},
    "bb4bd5bbec534efa8580af623fd44685":{
      "scriptId":"u7"},
    "57cb11226a4545ef8b11c4dbca8317a2":{
      "scriptId":"u8"},
    "c550a613d8c24f58b714078dac192577":{
      "scriptId":"u9"},
    "56f8b8b055db4323a33df79c02a01ed8":{
      "scriptId":"u10"},
    "056b80ccd12c477e99e0c8afa0fdfc05":{
      "scriptId":"u11"},
    "1e4586e05d074ddca13f8f20addef76d":{
      "scriptId":"u12"},
    "243c3972f15f4808865f07a66e176d9c":{
      "scriptId":"u13"},
    "95b1492439bb448d9505e581ab65a0c5":{
      "scriptId":"u14"},
    "29b9d6e8109f45ff8945e5b2a3a97c15":{
      "scriptId":"u15"},
    "f9c3c945c0d44c0684bc20de0996c2fc":{
      "scriptId":"u16"},
    "ae8e4202049b413bb2a02289034d1d91":{
      "scriptId":"u17"},
    "1884da2ed9f6487b916370d182ddbb0e":{
      "scriptId":"u18"},
    "628e69b07a5f4ffbbf9ff27bf28277ad":{
      "scriptId":"u19"},
    "d32505d853934107a1615a0f99f8546b":{
      "scriptId":"u20"},
    "b747d7a663ff44d191d8b4eebd05b86c":{
      "scriptId":"u21"},
    "991dae78e8614b60a6754008806a66d0":{
      "scriptId":"u22"},
    "1322a61c883c46639df3f237bea29896":{
      "scriptId":"u23"},
    "613597b2a85841e5bb957634dd63652c":{
      "scriptId":"u24"},
    "cbb988f47ca44fc6a40f19a092480428":{
      "scriptId":"u25"},
    "094df6fb7f9a4f43aafb5b21264c2d86":{
      "scriptId":"u26"},
    "dd5eb03c028d4fb9af7183b72c8bbcb3":{
      "scriptId":"u27"},
    "9921ad67b4f742d98cf9faa79e543206":{
      "scriptId":"u28"},
    "d2bd59441e3943ee94cfc912dd413d0c":{
      "scriptId":"u29"},
    "11ad6c791ab845a58daf0ca489fb57f2":{
      "scriptId":"u30"},
    "9195d58e61c14999b650bd3041d28df3":{
      "scriptId":"u31"},
    "8c211229eb0c44628f66b2519b39b1f2":{
      "scriptId":"u32"},
    "ad4e9aa45dad4fe98fa057909e7d5084":{
      "scriptId":"u33"},
    "d2dda79914c7456ab9d472d4b901dcc1":{
      "scriptId":"u34"},
    "9795bb6009684daa9fd4742c58a7ee7f":{
      "scriptId":"u35"},
    "c91b1226a3d04333b5171e9fe3626562":{
      "scriptId":"u36"},
    "eeb238ede0da45aba870e68fbdd89d5c":{
      "scriptId":"u37"},
    "c4d3ea99d7954036b9e39c30f7cf2ff5":{
      "scriptId":"u38"},
    "145474d0195b44cd89a2d0e3690d6b32":{
      "scriptId":"u39"},
    "35320f289585448c91bc10f254e76d44":{
      "scriptId":"u40"},
    "0fb3e80851b14156b3ea487ad88fd02c":{
      "scriptId":"u41"},
    "c9942c3a6b46468d8fea00c57fdeaad1":{
      "scriptId":"u42"},
    "780be42ff92f43a284ba860558a05f2f":{
      "scriptId":"u43"},
    "643342d1727747a1b476c485432b6225":{
      "scriptId":"u44"},
    "c26d0aeb342a4b859891298a70deb700":{
      "scriptId":"u45"},
    "b005b0b868ad4fcfb56f1e12c5bbeae2":{
      "scriptId":"u46"},
    "179d11c450474c09970143f4a8d7a1a5":{
      "scriptId":"u47"},
    "1e831509f3b243b4b1d84e5a409e43da":{
      "scriptId":"u48"},
    "01e547f6e2bc46ac8469ffb3e3602c2f":{
      "scriptId":"u49"},
    "52db46fd86b54f5b8de5fda4fb75bd29":{
      "scriptId":"u50"},
    "842e38a6b98240e39ebc46e81941ff0c":{
      "scriptId":"u51"},
    "871ee153cda24f888dd41ece0cd179e9":{
      "scriptId":"u52"},
    "323eaf330e864bd2820cdb7ec0f560d8":{
      "scriptId":"u53"},
    "02fc1b44730d4c539ecff87474ea2d60":{
      "scriptId":"u54"},
    "e515d56e60774b299ec1ef72176d2d49":{
      "scriptId":"u55"},
    "a270295c57b64cfcb2e233b463d5838b":{
      "scriptId":"u56"},
    "5f041507fd5b483b8b10adcafa9a7423":{
      "scriptId":"u57"},
    "220db36c24f841418b1d9f5332d122ba":{
      "scriptId":"u58"},
    "f9a454add4234d95b1c64c906f53e064":{
      "scriptId":"u59"},
    "bb6fab3a1b18462f9cd24eb7022ae9e8":{
      "scriptId":"u60"},
    "da02a420d38448c8806666545141294e":{
      "scriptId":"u61"},
    "31e795b3914a4ce78731c97c91dd8bc9":{
      "scriptId":"u62"},
    "1b75f652dfe34a4b9abe668d4120c105":{
      "scriptId":"u63"},
    "daff5fd3bb514706891b87704f64a490":{
      "scriptId":"u64"},
    "419142a0d65d46cca7f20eaf15312197":{
      "scriptId":"u65"},
    "02244269039a4d948f4fea323e7c01e6":{
      "scriptId":"u66"},
    "4938f412c580461aad6a2abb2ca8a800":{
      "scriptId":"u67"},
    "06b1cee48ba847089c03ba9132b7fa1f":{
      "scriptId":"u68"},
    "dfe18b3862724d6b927a6cbbfee3fa5a":{
      "scriptId":"u69"},
    "43658626e3354ad3b1e1642eaabcb30d":{
      "scriptId":"u70"},
    "8cf9a54fbd4c406e9b82f8050314b370":{
      "scriptId":"u71"},
    "b6a4beca02f04830bbe15419034bdfff":{
      "scriptId":"u72"},
    "cc63c420a43642e2a89a6a7fedde030c":{
      "scriptId":"u73"},
    "d36ad0521dc14241a14797313be91c18":{
      "scriptId":"u74"},
    "c97e16d2ea2b4144a9ba2ae074ea20c9":{
      "scriptId":"u75"},
    "36f8dae8270a494e9dd9e4c7ea89307f":{
      "scriptId":"u76"},
    "7abfcbc344d64118a009010de8a49a26":{
      "scriptId":"u77"},
    "0cdcb83d188148828d807374df2d63b4":{
      "scriptId":"u78"},
    "059f246b1ffb4dd08f8a56edef6b13b4":{
      "scriptId":"u79"},
    "b9161238dea94f649e2cb8b27ae9f53c":{
      "scriptId":"u80"},
    "76f68c0b4a0146a388b13e713439f2fc":{
      "scriptId":"u81"},
    "085ed80f9ae845b8b29b9f590b78dbf5":{
      "scriptId":"u82"},
    "ff47921e205a454898f7955d940fa7ed":{
      "scriptId":"u83"},
    "39c04b23dfdf462990652c5861233666":{
      "scriptId":"u84"},
    "1870a4da94d04c589272f2c1a75a65d9":{
      "scriptId":"u85"},
    "76ae9e357d6c46c2b4705553364fc11e":{
      "scriptId":"u86"},
    "ff23902fbd954f8aba5d9b0fa0aee833":{
      "scriptId":"u87"},
    "2045b1d50b214312a81428f6690b6ad0":{
      "scriptId":"u88"},
    "e554eadb14024631bf8a80836bef2b98":{
      "scriptId":"u89"},
    "f199aa9a820347069f5076b487ce6d56":{
      "scriptId":"u90"},
    "9649b5acda6b48f895c600ca47abc23d":{
      "scriptId":"u91"},
    "404aa6df20424c8480aa97b3f1844393":{
      "scriptId":"u92"},
    "c8c2ff1af87b4c0697748c97e05e614e":{
      "scriptId":"u93"},
    "b4733d7a5a08471880053993f0d198df":{
      "scriptId":"u94"},
    "31d97334f5e7470ea6357fc43a7e7583":{
      "scriptId":"u95"},
    "539b0161ae0344ea8f3879913ab1c547":{
      "scriptId":"u96"},
    "0e40a272d0534f22a0c87f84c919a3bb":{
      "scriptId":"u97"}}});