$axure.loadCurrentPage({
  "url":"userinfo.html",
  "generationDate":new Date(1411547600648.6),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b81cfc630e514780b357c19badc7a6ac",
    "type":"Axure:Page",
    "name":"UserInfo",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0a6a3b2c9698492995a5ef88997301d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":210},
            "size":{
              "width":1030,
              "height":620}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e541e86dc495423eab3af647b969c4bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":210},
                "size":{
                  "width":1030,
                  "height":620}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/guanzhu/u0.png"}},
{
          "id":"94dacbed580b4921aa8f537c1e5552ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":32},
            "size":{
              "width":800,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7d7da4f6285474998bfc825bb8c7434",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":32},
                "size":{
                  "width":800,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"8910646dfa964b449bbe629f0db8e9e6",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":825,
              "y":70},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"ed53f56b84724db58a0d5a176a758792",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1055,
              "y":70},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b6bc90820524462bb175d22b81a2f5a1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":6},
            "size":{
              "width":150,
              "height":116}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7b8d19281084edd9649d41c5aa65652",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":6},
                "size":{
                  "width":150,
                  "height":116}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u10.png"}},
{
          "id":"4bd74ed05a62474f9b2bdd0325dd4bf0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":1228,
              "y":5},
            "size":{
              "width":22,
              "height":215}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39c0169294d3402b88df8676c82dd00c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":1228,
                  "y":5},
                "size":{
                  "width":22,
                  "height":215}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"165d6164e3e14c2c8ca0ec7570f34012",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1079,
              "y":11},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd10e8271a49403e9e115d0737fb0d49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1079,
                  "y":11},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d74529c348134a9489ccbc1564b5ba97",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":999,
              "y":8},
            "size":{
              "width":20,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e10b616f9d074fbd98f02ec0cfe5c885",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":999,
                  "y":8},
                "size":{
                  "width":20,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/livelist/u72.png"}},
{
          "id":"a41d831de2aa4bb98a47902ee9b4b2a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1029,
              "y":11},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b48f3683f554f02aff969bab2377e0e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1029,
                  "y":11},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c8b91a125a934f0cb769fb371fe9bb58",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1177,
              "y":11},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e700f43fb15e49d29965db63f3859f53",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1177,
                  "y":11},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab3dccd4444a44b4a239a811dc2f9e3c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":1116,
              "y":11},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab507c6bb7384064b69c5bf7b48273f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":1116,
                  "y":11},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 UserInfo",
                      "target":{
                        "targetType":"page",
                        "url":"userinfo.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cf15c8a261444dc5a600fd47aa265830",
          "label":"",
          "type":"treeNodeObject",
          "styleType":"treeNodeObject",
          "visible":true,
          "style":{
            "location":{
              "x":187,
              "y":260},
            "size":{
              "width":100,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d20bab09e27d4779926a522b7010abdf",
              "label":"",
              "type":"treeNodeObject",
              "styleType":"treeNodeObject",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "size":{
                  "width":80,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0f22fe9bb24f410482a733bb9ad0ca48",
                  "label":"",
                  "isContained":true,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5da3e9dc8f884047974c8f9b1ffceed8",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0000FF,
                          "opacity":1},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9b02f5c09aaa4c96b98d45a652c8f11f",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":20,
                      "y":20},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c5c6ff52171e4d5593222d753e2e49db",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0000FF,
                          "opacity":1},
                        "location":{
                          "x":20,
                          "y":20},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"46b8b7ef697f4a849ec0295561dee1c8",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF0000FF,
                              "opacity":1},
                            "location":{
                              "x":20,
                              "y":20},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 s_MyCourse",
                              "target":{
                                "targetType":"page",
                                "url":"s_mycourse.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "buttonShapeId":"c5c6ff52171e4d5593222d753e2e49db"},
{
                  "id":"a6d20fb3c28a423aa338e469d0791c79",
                  "label":"",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "selected":{
}},
                    "location":{
                      "x":6,
                      "y":6},
                    "size":{
                      "width":9,
                      "height":9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ff91b03f6d514bd1a62bf5dd989cb39a",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
}},
                        "location":{
                          "x":6,
                          "y":6},
                        "size":{
                          "width":9,
                          "height":9}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/guanzhu/u22.png",
                    "selected~":"images/guanzhu/u22_selected.png"}},
{
                  "id":"b027ffa18f9d4d36b8ec4f064942f545",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":20,
                      "y":40},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4829ee70e64f4769a283f695d4f72627",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0000FF,
                          "opacity":1},
                        "location":{
                          "x":20,
                          "y":40},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"ce9f7724a3f042b5967d131918aed190",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF0000FF,
                              "opacity":1},
                            "location":{
                              "x":20,
                              "y":40},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 s_MyTest",
                              "target":{
                                "targetType":"page",
                                "url":"s_mytest.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "buttonShapeId":"4829ee70e64f4769a283f695d4f72627"},
{
                  "id":"e089e83d071b46da880bf7019dee7de5",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":20,
                      "y":60},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8406ecc31c0940e89d4e23a04cbfec23",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0000FF,
                          "opacity":1},
                        "location":{
                          "x":20,
                          "y":60},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"03f7de5d69ae42219ff3de845580de1f",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF0000FF,
                              "opacity":1},
                            "location":{
                              "x":20,
                              "y":60},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 s_MyComment",
                              "target":{
                                "targetType":"page",
                                "url":"s_mycomment.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "buttonShapeId":"8406ecc31c0940e89d4e23a04cbfec23"}],
              "buttonShapeId":"0f22fe9bb24f410482a733bb9ad0ca48"}]},
{
          "id":"dff5bfce57994d849179a401fdf2fc26",
          "label":"",
          "type":"treeNodeObject",
          "styleType":"treeNodeObject",
          "visible":true,
          "style":{
            "location":{
              "x":187,
              "y":350},
            "size":{
              "width":113,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a290814b8de842a9bcee59cc4546eb11",
              "label":"",
              "type":"treeNodeObject",
              "styleType":"treeNodeObject",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "size":{
                  "width":80,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9f7bd47fe20b4b99be38fba901793ad7",
                  "label":"",
                  "isContained":true,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f945bd13cba349b6bdf7731f758f6768",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0000FF,
                          "opacity":1},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"72fce801a6ae4985a3a741450507c571",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":20,
                      "y":20},
                    "size":{
                      "width":93,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"752d90bb83564be9807421bf4a061687",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0000FF,
                          "opacity":1},
                        "location":{
                          "x":20,
                          "y":20},
                        "size":{
                          "width":93,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"b712abe077b34192838078d94a70621c",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF0000FF,
                              "opacity":1},
                            "location":{
                              "x":20,
                              "y":20},
                            "size":{
                              "width":93,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 t_Machine",
                              "target":{
                                "targetType":"page",
                                "url":"t_machine.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "buttonShapeId":"752d90bb83564be9807421bf4a061687"},
{
                  "id":"2bba6272eac64739bb37d5cc64948502",
                  "label":"",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "selected":{
}},
                    "location":{
                      "x":6,
                      "y":6},
                    "size":{
                      "width":9,
                      "height":9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"238d68dbf4dc431189612c0df9716f8a",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
}},
                        "location":{
                          "x":6,
                          "y":6},
                        "size":{
                          "width":9,
                          "height":9}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/guanzhu/u22.png",
                    "selected~":"images/guanzhu/u22_selected.png"}},
{
                  "id":"98a9c4d5c9864cfeab5211d28200e394",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":20,
                      "y":40},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1c04ad9132dd4fbfa46b6292a036990e",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0000FF,
                          "opacity":1},
                        "location":{
                          "x":20,
                          "y":40},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"aa397801af554086a554a1d12195967f",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF0000FF,
                              "opacity":1},
                            "location":{
                              "x":20,
                              "y":40},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 t_MyLive",
                              "target":{
                                "targetType":"page",
                                "url":"t_mylive.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "buttonShapeId":"1c04ad9132dd4fbfa46b6292a036990e"},
{
                  "id":"8ff912c7e36d476093039ddfcd59d9be",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":20,
                      "y":60},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"56874a8fde404d1f99e870335222c4c1",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0000FF,
                          "opacity":1},
                        "location":{
                          "x":20,
                          "y":60},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"1e353b34130548a5bd138a1133d71ed8",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF0000FF,
                              "opacity":1},
                            "location":{
                              "x":20,
                              "y":60},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 t_MyVod",
                              "target":{
                                "targetType":"page",
                                "url":"t_myvod.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "buttonShapeId":"56874a8fde404d1f99e870335222c4c1"},
{
                  "id":"095da0321cb848f7b06d7f4f376a331b",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":20,
                      "y":80},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"94f00857bf3f4e5f9365e411b6225064",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0000FF,
                          "opacity":1},
                        "location":{
                          "x":20,
                          "y":80},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"c938d1456a9c4224b7ff081b62a4a7f5",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF0000FF,
                              "opacity":1},
                            "location":{
                              "x":20,
                              "y":80},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 t_QuestionMgr",
                              "target":{
                                "targetType":"page",
                                "url":"t_questionmgr.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "buttonShapeId":"94f00857bf3f4e5f9365e411b6225064"},
{
                  "id":"9293c9821a2f457db2c60477255a3c61",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":20,
                      "y":100},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"66c597c2b9af4174bbe49dcb29374df0",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0000FF,
                          "opacity":1},
                        "location":{
                          "x":20,
                          "y":100},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"e77a9b7eddaf4c2e98de7ee8ec8a1b28",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF0000FF,
                              "opacity":1},
                            "location":{
                              "x":20,
                              "y":100},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 t_TestMgr",
                              "target":{
                                "targetType":"page",
                                "url":"t_testmgr.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "buttonShapeId":"66c597c2b9af4174bbe49dcb29374df0"}],
              "buttonShapeId":"9f7bd47fe20b4b99be38fba901793ad7"}]},
{
          "id":"092b9b08fb4c40e8b89bc1cee71d3e19",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1033,
              "y":224},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b42cd827e81d46bfa4def99c02711e44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1033,
                  "y":224},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"74b2a34b6fe340ce80ada8d9404e416e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1102,
              "y":224},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13e999a9615844558d7cf30ccb4c9b85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1102,
                  "y":224},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c9e1b944844c4a03a36074b34e640b0f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":282},
            "size":{
              "width":57,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/guanzhu/u62_line.png"}},
{
          "id":"2e785d4ed8244bc1a986af1ce1cec7d9",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":224},
            "size":{
              "width":903,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/guanzhu/u63_line.png"}},
{
          "id":"762f528641db42cdb95392cb98164b62",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":148,
              "y":224},
            "size":{
              "width":10,
              "height":68}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/guanzhu/u64_line.png"}},
{
          "id":"c228793b59104b00ba151298c40cd54e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":840},
            "size":{
              "width":1030,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a887ffe507b34128ab1b23b839c59017",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":840},
                "size":{
                  "width":1030,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u185.png"}},
{
          "id":"ea337434fef344f58b0ac2fa51f7f5b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":270},
            "size":{
              "width":860,
              "height":540}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"236cf3ba48b7484fa3aaabdcfd4768ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":330,
                  "y":270},
                "size":{
                  "width":860,
                  "height":540}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/userinfo/u65.png"}},
{
          "id":"f35a978445374a8cae914349df58a0da",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":679,
              "y":350},
            "size":{
              "width":87,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f7a725f91bb4226afd1a0c8db837408",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":679,
                  "y":350},
                "size":{
                  "width":87,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"639a97489fa54bb29afeb98713d60b85",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":679,
              "y":376},
            "size":{
              "width":87,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1794f5647fb9480b8858bf3aa32e4756",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":679,
                  "y":376},
                "size":{
                  "width":87,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"489d65ad33e1477580981d55d7dea2bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":679,
              "y":402},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52cefd1185884475a7b89dac3d8026c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":679,
                  "y":402},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d013d21b87e3466db500840856571044",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":679,
              "y":428},
            "size":{
              "width":87,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7331c0353cf54e55bfdf1b187ad0118b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":679,
                  "y":428},
                "size":{
                  "width":87,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ccc7f3dd7f9944ac90fd53f6a6ab9b98",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":679,
              "y":454},
            "size":{
              "width":61,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ad9258fcb904cef8d86052c7038997b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":679,
                  "y":454},
                "size":{
                  "width":61,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"660907c0cc8042fa8877908ff539f49a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":679,
              "y":480},
            "size":{
              "width":61,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dada282284b946a48d542fba6f882df1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":679,
                  "y":480},
                "size":{
                  "width":61,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3c7fe7a65a474d748445a2e6168d8fdc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":679,
              "y":506},
            "size":{
              "width":61,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d64ef455c1d844d4b64ea41733b9ab9a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":679,
                  "y":506},
                "size":{
                  "width":61,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"83da273cec6b414da76dbd644c504a0c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":679,
              "y":324},
            "size":{
              "width":61,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9caf32aa1cad4b54b71aa0744862950f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":679,
                  "y":324},
                "size":{
                  "width":61,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"981a328d52ed48f98104e131cb1f7256",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":679,
              "y":298},
            "size":{
              "width":74,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c59d378125e4ce0bf5ede86213adc68",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":679,
                  "y":298},
                "size":{
                  "width":74,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d07e5bdca3b747f9b1707589e1221ec3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":307},
            "size":{
              "width":140,
              "height":133}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68fd4d7cc64d4fdc9d417e659f6365de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":307},
                "size":{
                  "width":140,
                  "height":133}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/userinfo/u85.png"}},
{
          "id":"d07271c84b5543acb2c10137e971bb45",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":679,
              "y":560},
            "size":{
              "width":61,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"febc27cbd00145ba9c7c26b038fbc55c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":679,
                  "y":560},
                "size":{
                  "width":61,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0972754604364a419cad3f5691e750c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":679,
              "y":534},
            "size":{
              "width":61,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2059f3a4627a4af48a8799a01aa88a11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":679,
                  "y":534},
                "size":{
                  "width":61,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"56fb4e6be68548cfad84859413c82fa8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":679,
              "y":586},
            "size":{
              "width":61,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b29f071803b4627abb4aadad4dfd0fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":679,
                  "y":586},
                "size":{
                  "width":61,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"57512938a7564857b990e223b04b3697",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":825,
              "y":312},
            "size":{
              "width":22,
              "height":248}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"406e3ccbb1664a3caf9c8a1b0e4fab6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":825,
                  "y":312},
                "size":{
                  "width":22,
                  "height":248}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3a9e5e6538854ce480cf9b723043994c",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":197,
              "y":480},
            "size":{
              "width":100,
              "height":154}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"204d3549522945fab372234964bf8e4e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":34},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9824ee6ad4a046e28ca5b3a893be4889",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":34},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "interactionMap":{
                "onClick":{
                  "description":"OnClick",
                  "cases":[{
                      "description":"用例 1",
                      "isNewIfGroup":false,
                      "actions":[{
                          "action":"linkWindow",
                          "description":"在 当前窗口 打开 UserInfo",
                          "target":{
                            "targetType":"page",
                            "url":"userinfo.html",
                            "includeVariables":true},
                          "linkType":"current"}]}]}},
              "tabbable":true,
              "images":{
                "normal~":"images/guanzhu/u72.png"}},
{
              "id":"4c7a8796493e46bcba0a12135099ab0e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":64},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2538edd7ca8a4359a11be8c0306f28dd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":64},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "interactionMap":{
                "onClick":{
                  "description":"OnClick",
                  "cases":[{
                      "description":"用例 1",
                      "isNewIfGroup":false,
                      "actions":[{
                          "action":"linkWindow",
                          "description":"在 当前窗口 打开 ChangePwd",
                          "target":{
                            "targetType":"page",
                            "url":"changepwd.html",
                            "includeVariables":true},
                          "linkType":"current"}]}]}},
              "tabbable":true,
              "images":{
                "normal~":"images/guanzhu/u72.png"}},
{
              "id":"faa4ee8901c641b7b5718da28478286b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":94},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"08d9e19015364193a6c643c105d9ca57",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":94},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "interactionMap":{
                "onClick":{
                  "description":"OnClick",
                  "cases":[{
                      "description":"用例 1",
                      "isNewIfGroup":false,
                      "actions":[{
                          "action":"linkWindow",
                          "description":"在 当前窗口 打开 Money",
                          "target":{
                            "targetType":"page",
                            "url":"money.html",
                            "includeVariables":true},
                          "linkType":"current"}]}]}},
              "tabbable":true,
              "images":{
                "normal~":"images/guanzhu/u72.png"}},
{
              "id":"a46a551f068e4c04b7ecd8a07e728ed1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":124},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c1958d7b552d4d848d5fe1243ecd4f4f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":124},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "interactionMap":{
                "onClick":{
                  "description":"OnClick",
                  "cases":[{
                      "description":"用例 1",
                      "isNewIfGroup":false,
                      "actions":[{
                          "action":"linkWindow",
                          "description":"在 当前窗口 打开 Jiaoyi",
                          "target":{
                            "targetType":"page",
                            "url":"jiaoyi.html",
                            "includeVariables":true},
                          "linkType":"current"}]}]}},
              "tabbable":true,
              "images":{
                "normal~":"images/guanzhu/u78.png"}},
{
              "id":"37dd627a7bb44ff59e57388f5b6e7d65",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "size":{
                  "width":100,
                  "height":34}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8ebcc43d6f234dbdbfee798717eaa46b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "size":{
                      "width":100,
                      "height":34}},
                  "adaptiveStyles":{
}}],
              "interactionMap":{
                "onClick":{
                  "description":"OnClick",
                  "cases":[{
                      "description":"用例 1",
                      "isNewIfGroup":false,
                      "actions":[{
                          "action":"linkWindow",
                          "description":"在 当前窗口 打开 Guanzhu",
                          "target":{
                            "targetType":"page",
                            "url":"guanzhu.html",
                            "includeVariables":true},
                          "linkType":"current"}]}]}},
              "tabbable":true,
              "images":{
                "normal~":"images/guanzhu/u70.png"}}]},
{
          "id":"33b6596c42d34d618b820c00d74d061d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":152},
            "size":{
              "width":1030,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6461e4b7971485da6ca5c67074954a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":152},
                "size":{
                  "width":1030,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u12.png"}},
{
          "id":"a7f0597620774a44b40c1895cbccab56",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":200,
              "y":164},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5aae319264c242b1be6a49d76b1eaf3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":200,
                  "y":164},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7c3b6b736b4e4b19addf5ad91134271e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":253,
              "y":164},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5416eea854234c5cb72c5dffee359be9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":253,
                  "y":164},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 LiveList",
                      "target":{
                        "targetType":"page",
                        "url":"livelist.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a0bc4bc789f74e15a879a55bfb457e63",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":320,
              "y":164},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b507322d27e6458b9925d77c5e82291f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":320,
                  "y":164},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 VodList",
                      "target":{
                        "targetType":"page",
                        "url":"vodlist.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e74820f9d13641a6b2658a43bb5b2e55",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":390,
              "y":164},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c000456043f246c9893a19a6f9ea090e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":390,
                  "y":164},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 SchoolList",
                      "target":{
                        "targetType":"page",
                        "url":"schoollist.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e769807466554134a3a5fe405f64f1f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":453,
              "y":164},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc514359701a4cf58ab83fb7520f8eb0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":453,
                  "y":164},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 TeacherList",
                      "target":{
                        "targetType":"page",
                        "url":"teacherlist.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "0a6a3b2c9698492995a5ef88997301d7":{
      "scriptId":"u0"},
    "e541e86dc495423eab3af647b969c4bc":{
      "scriptId":"u1"},
    "94dacbed580b4921aa8f537c1e5552ab":{
      "scriptId":"u2"},
    "b7d7da4f6285474998bfc825bb8c7434":{
      "scriptId":"u3"},
    "8910646dfa964b449bbe629f0db8e9e6":{
      "scriptId":"u4"},
    "ed53f56b84724db58a0d5a176a758792":{
      "scriptId":"u5"},
    "b6bc90820524462bb175d22b81a2f5a1":{
      "scriptId":"u6"},
    "c7b8d19281084edd9649d41c5aa65652":{
      "scriptId":"u7"},
    "4bd74ed05a62474f9b2bdd0325dd4bf0":{
      "scriptId":"u8"},
    "39c0169294d3402b88df8676c82dd00c":{
      "scriptId":"u9"},
    "165d6164e3e14c2c8ca0ec7570f34012":{
      "scriptId":"u10"},
    "fd10e8271a49403e9e115d0737fb0d49":{
      "scriptId":"u11"},
    "d74529c348134a9489ccbc1564b5ba97":{
      "scriptId":"u12"},
    "e10b616f9d074fbd98f02ec0cfe5c885":{
      "scriptId":"u13"},
    "a41d831de2aa4bb98a47902ee9b4b2a6":{
      "scriptId":"u14"},
    "1b48f3683f554f02aff969bab2377e0e":{
      "scriptId":"u15"},
    "c8b91a125a934f0cb769fb371fe9bb58":{
      "scriptId":"u16"},
    "e700f43fb15e49d29965db63f3859f53":{
      "scriptId":"u17"},
    "ab3dccd4444a44b4a239a811dc2f9e3c":{
      "scriptId":"u18"},
    "ab507c6bb7384064b69c5bf7b48273f1":{
      "scriptId":"u19"},
    "cf15c8a261444dc5a600fd47aa265830":{
      "scriptId":"u20"},
    "d20bab09e27d4779926a522b7010abdf":{
      "scriptId":"u21"},
    "a6d20fb3c28a423aa338e469d0791c79":{
      "scriptId":"u22"},
    "ff91b03f6d514bd1a62bf5dd989cb39a":{
      "scriptId":"u23"},
    "0f22fe9bb24f410482a733bb9ad0ca48":{
      "scriptId":"u24"},
    "5da3e9dc8f884047974c8f9b1ffceed8":{
      "scriptId":"u25"},
    "9b02f5c09aaa4c96b98d45a652c8f11f":{
      "scriptId":"u26"},
    "c5c6ff52171e4d5593222d753e2e49db":{
      "scriptId":"u27"},
    "46b8b7ef697f4a849ec0295561dee1c8":{
      "scriptId":"u28"},
    "b027ffa18f9d4d36b8ec4f064942f545":{
      "scriptId":"u29"},
    "4829ee70e64f4769a283f695d4f72627":{
      "scriptId":"u30"},
    "ce9f7724a3f042b5967d131918aed190":{
      "scriptId":"u31"},
    "e089e83d071b46da880bf7019dee7de5":{
      "scriptId":"u32"},
    "8406ecc31c0940e89d4e23a04cbfec23":{
      "scriptId":"u33"},
    "03f7de5d69ae42219ff3de845580de1f":{
      "scriptId":"u34"},
    "dff5bfce57994d849179a401fdf2fc26":{
      "scriptId":"u35"},
    "a290814b8de842a9bcee59cc4546eb11":{
      "scriptId":"u36"},
    "2bba6272eac64739bb37d5cc64948502":{
      "scriptId":"u37"},
    "238d68dbf4dc431189612c0df9716f8a":{
      "scriptId":"u38"},
    "9f7bd47fe20b4b99be38fba901793ad7":{
      "scriptId":"u39"},
    "f945bd13cba349b6bdf7731f758f6768":{
      "scriptId":"u40"},
    "72fce801a6ae4985a3a741450507c571":{
      "scriptId":"u41"},
    "752d90bb83564be9807421bf4a061687":{
      "scriptId":"u42"},
    "b712abe077b34192838078d94a70621c":{
      "scriptId":"u43"},
    "98a9c4d5c9864cfeab5211d28200e394":{
      "scriptId":"u44"},
    "1c04ad9132dd4fbfa46b6292a036990e":{
      "scriptId":"u45"},
    "aa397801af554086a554a1d12195967f":{
      "scriptId":"u46"},
    "8ff912c7e36d476093039ddfcd59d9be":{
      "scriptId":"u47"},
    "56874a8fde404d1f99e870335222c4c1":{
      "scriptId":"u48"},
    "1e353b34130548a5bd138a1133d71ed8":{
      "scriptId":"u49"},
    "095da0321cb848f7b06d7f4f376a331b":{
      "scriptId":"u50"},
    "94f00857bf3f4e5f9365e411b6225064":{
      "scriptId":"u51"},
    "c938d1456a9c4224b7ff081b62a4a7f5":{
      "scriptId":"u52"},
    "9293c9821a2f457db2c60477255a3c61":{
      "scriptId":"u53"},
    "66c597c2b9af4174bbe49dcb29374df0":{
      "scriptId":"u54"},
    "e77a9b7eddaf4c2e98de7ee8ec8a1b28":{
      "scriptId":"u55"},
    "092b9b08fb4c40e8b89bc1cee71d3e19":{
      "scriptId":"u56"},
    "b42cd827e81d46bfa4def99c02711e44":{
      "scriptId":"u57"},
    "74b2a34b6fe340ce80ada8d9404e416e":{
      "scriptId":"u58"},
    "13e999a9615844558d7cf30ccb4c9b85":{
      "scriptId":"u59"},
    "c9e1b944844c4a03a36074b34e640b0f":{
      "scriptId":"u60"},
    "2e785d4ed8244bc1a986af1ce1cec7d9":{
      "scriptId":"u61"},
    "762f528641db42cdb95392cb98164b62":{
      "scriptId":"u62"},
    "c228793b59104b00ba151298c40cd54e":{
      "scriptId":"u63"},
    "a887ffe507b34128ab1b23b839c59017":{
      "scriptId":"u64"},
    "ea337434fef344f58b0ac2fa51f7f5b3":{
      "scriptId":"u65"},
    "236cf3ba48b7484fa3aaabdcfd4768ec":{
      "scriptId":"u66"},
    "f35a978445374a8cae914349df58a0da":{
      "scriptId":"u67"},
    "6f7a725f91bb4226afd1a0c8db837408":{
      "scriptId":"u68"},
    "639a97489fa54bb29afeb98713d60b85":{
      "scriptId":"u69"},
    "1794f5647fb9480b8858bf3aa32e4756":{
      "scriptId":"u70"},
    "489d65ad33e1477580981d55d7dea2bb":{
      "scriptId":"u71"},
    "52cefd1185884475a7b89dac3d8026c8":{
      "scriptId":"u72"},
    "d013d21b87e3466db500840856571044":{
      "scriptId":"u73"},
    "7331c0353cf54e55bfdf1b187ad0118b":{
      "scriptId":"u74"},
    "ccc7f3dd7f9944ac90fd53f6a6ab9b98":{
      "scriptId":"u75"},
    "9ad9258fcb904cef8d86052c7038997b":{
      "scriptId":"u76"},
    "660907c0cc8042fa8877908ff539f49a":{
      "scriptId":"u77"},
    "dada282284b946a48d542fba6f882df1":{
      "scriptId":"u78"},
    "3c7fe7a65a474d748445a2e6168d8fdc":{
      "scriptId":"u79"},
    "d64ef455c1d844d4b64ea41733b9ab9a":{
      "scriptId":"u80"},
    "83da273cec6b414da76dbd644c504a0c":{
      "scriptId":"u81"},
    "9caf32aa1cad4b54b71aa0744862950f":{
      "scriptId":"u82"},
    "981a328d52ed48f98104e131cb1f7256":{
      "scriptId":"u83"},
    "9c59d378125e4ce0bf5ede86213adc68":{
      "scriptId":"u84"},
    "d07e5bdca3b747f9b1707589e1221ec3":{
      "scriptId":"u85"},
    "68fd4d7cc64d4fdc9d417e659f6365de":{
      "scriptId":"u86"},
    "d07271c84b5543acb2c10137e971bb45":{
      "scriptId":"u87"},
    "febc27cbd00145ba9c7c26b038fbc55c":{
      "scriptId":"u88"},
    "0972754604364a419cad3f5691e750c1":{
      "scriptId":"u89"},
    "2059f3a4627a4af48a8799a01aa88a11":{
      "scriptId":"u90"},
    "56fb4e6be68548cfad84859413c82fa8":{
      "scriptId":"u91"},
    "2b29f071803b4627abb4aadad4dfd0fb":{
      "scriptId":"u92"},
    "57512938a7564857b990e223b04b3697":{
      "scriptId":"u93"},
    "406e3ccbb1664a3caf9c8a1b0e4fab6b":{
      "scriptId":"u94"},
    "3a9e5e6538854ce480cf9b723043994c":{
      "scriptId":"u95"},
    "37dd627a7bb44ff59e57388f5b6e7d65":{
      "scriptId":"u96"},
    "8ebcc43d6f234dbdbfee798717eaa46b":{
      "scriptId":"u97"},
    "204d3549522945fab372234964bf8e4e":{
      "scriptId":"u98"},
    "9824ee6ad4a046e28ca5b3a893be4889":{
      "scriptId":"u99"},
    "4c7a8796493e46bcba0a12135099ab0e":{
      "scriptId":"u100"},
    "2538edd7ca8a4359a11be8c0306f28dd":{
      "scriptId":"u101"},
    "faa4ee8901c641b7b5718da28478286b":{
      "scriptId":"u102"},
    "08d9e19015364193a6c643c105d9ca57":{
      "scriptId":"u103"},
    "a46a551f068e4c04b7ecd8a07e728ed1":{
      "scriptId":"u104"},
    "c1958d7b552d4d848d5fe1243ecd4f4f":{
      "scriptId":"u105"},
    "33b6596c42d34d618b820c00d74d061d":{
      "scriptId":"u106"},
    "f6461e4b7971485da6ca5c67074954a4":{
      "scriptId":"u107"},
    "a7f0597620774a44b40c1895cbccab56":{
      "scriptId":"u108"},
    "5aae319264c242b1be6a49d76b1eaf3c":{
      "scriptId":"u109"},
    "7c3b6b736b4e4b19addf5ad91134271e":{
      "scriptId":"u110"},
    "5416eea854234c5cb72c5dffee359be9":{
      "scriptId":"u111"},
    "a0bc4bc789f74e15a879a55bfb457e63":{
      "scriptId":"u112"},
    "b507322d27e6458b9925d77c5e82291f":{
      "scriptId":"u113"},
    "e74820f9d13641a6b2658a43bb5b2e55":{
      "scriptId":"u114"},
    "c000456043f246c9893a19a6f9ea090e":{
      "scriptId":"u115"},
    "e769807466554134a3a5fe405f64f1f9":{
      "scriptId":"u116"},
    "fc514359701a4cf58ab83fb7520f8eb0":{
      "scriptId":"u117"}}});