$axure.loadCurrentPage({
  "url":"jiaoyi.html",
  "generationDate":new Date(1411547601104.9),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4aba7af98411481ea4cd019d84b7a709",
    "type":"Axure:Page",
    "name":"Jiaoyi",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0e624873977b4b9abc1109455bb4437f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":210},
            "size":{
              "width":1030,
              "height":620}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"790335e4598e49eb8183519559718872",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":210},
                "size":{
                  "width":1030,
                  "height":620}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/guanzhu/u0.png"}},
{
          "id":"43ef8e9d3c35411fb326472fe92edbfd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":32},
            "size":{
              "width":800,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22d984a068ba46158aedd4c962746cb0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":32},
                "size":{
                  "width":800,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"ca15cb5eca094484adee925e8b434a77",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":825,
              "y":70},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"afcc510127f9444fad6e19b66b004e9a",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":1055,
              "y":70},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"0b13057085134ac6a4eb019b3b24fc48",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":6},
            "size":{
              "width":150,
              "height":116}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62b53333bcc44bf69cce7b9327fa9c9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":6},
                "size":{
                  "width":150,
                  "height":116}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u10.png"}},
{
          "id":"46db73ebc63c4c778ffd4be18a6f9135",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":1228,
              "y":5},
            "size":{
              "width":22,
              "height":215}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1e6205ff74b43f68b39ba3faaa5b7c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":1228,
                  "y":5},
                "size":{
                  "width":22,
                  "height":215}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fa2c937e3fc3407c91393d42db7a7ac3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1079,
              "y":11},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b56fa6d29974c30a7e8743c2f6be00e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1079,
                  "y":11},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c31e70d21c9249178fbe74e736db54f5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":999,
              "y":8},
            "size":{
              "width":20,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7531af5d4730446a94a7f2773b29d8f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":999,
                  "y":8},
                "size":{
                  "width":20,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/livelist/u72.png"}},
{
          "id":"59b08ce094ac4bcaa9143b507599e19d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1029,
              "y":11},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3715b84387a44a5ad48378cd4c77a91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1029,
                  "y":11},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"85d5f3b11ad6453089a4712c59e5c9a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1177,
              "y":11},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea57be9fc3c643519c7686a118a92ff2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1177,
                  "y":11},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d839a2471f324ed69c5bf7839f411725",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":1116,
              "y":11},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9868aa24ef6b4fe88a6775066b8fa94c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":1116,
                  "y":11},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 UserInfo",
                      "target":{
                        "targetType":"page",
                        "url":"userinfo.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cdd14ef9df2b4b7e988a6bfcfa4e6e79",
          "label":"",
          "type":"treeNodeObject",
          "styleType":"treeNodeObject",
          "visible":true,
          "style":{
            "location":{
              "x":187,
              "y":260},
            "size":{
              "width":100,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48006ce5bf2f4114b484daefc220153e",
              "label":"",
              "type":"treeNodeObject",
              "styleType":"treeNodeObject",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "size":{
                  "width":80,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"39cee26f22ad43a3bfc38fffe0c960b2",
                  "label":"",
                  "isContained":true,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0538c1f49d49459f8b4711585eace9ba",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0000FF,
                          "opacity":1},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ed83429f52184887bf8b9a7daee65c7e",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":20,
                      "y":20},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d9b6526c50444e438cd1c89ad2aedabb",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0000FF,
                          "opacity":1},
                        "location":{
                          "x":20,
                          "y":20},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"8eb37fb0febe4211867505b3dbe18b4b",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF0000FF,
                              "opacity":1},
                            "location":{
                              "x":20,
                              "y":20},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 s_MyCourse",
                              "target":{
                                "targetType":"page",
                                "url":"s_mycourse.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "buttonShapeId":"d9b6526c50444e438cd1c89ad2aedabb"},
{
                  "id":"766c6b257c274c37b2e121a5e1e40a3e",
                  "label":"",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "selected":{
}},
                    "location":{
                      "x":6,
                      "y":6},
                    "size":{
                      "width":9,
                      "height":9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3df13c31dae644f8907006b59ffc330e",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
}},
                        "location":{
                          "x":6,
                          "y":6},
                        "size":{
                          "width":9,
                          "height":9}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/guanzhu/u22.png",
                    "selected~":"images/guanzhu/u22_selected.png"}},
{
                  "id":"cf40050496544fa69e4e0259893ddef8",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":20,
                      "y":40},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"05bfff0adddb47dc8d2c37d12c7fa49e",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0000FF,
                          "opacity":1},
                        "location":{
                          "x":20,
                          "y":40},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"9cc0d9a1d53c4b4a83b6346a29eb87d7",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF0000FF,
                              "opacity":1},
                            "location":{
                              "x":20,
                              "y":40},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 s_MyTest",
                              "target":{
                                "targetType":"page",
                                "url":"s_mytest.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "buttonShapeId":"05bfff0adddb47dc8d2c37d12c7fa49e"},
{
                  "id":"75b5da255b484d8b9f52053e27f3f88e",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":20,
                      "y":60},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e06d8987eac84841b8fe70a0f5ce8a43",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0000FF,
                          "opacity":1},
                        "location":{
                          "x":20,
                          "y":60},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"bfb76c3960d54a67ac8e7ecb8e6e5ba7",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF0000FF,
                              "opacity":1},
                            "location":{
                              "x":20,
                              "y":60},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 s_MyComment",
                              "target":{
                                "targetType":"page",
                                "url":"s_mycomment.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "buttonShapeId":"e06d8987eac84841b8fe70a0f5ce8a43"}],
              "buttonShapeId":"39cee26f22ad43a3bfc38fffe0c960b2"}]},
{
          "id":"8787b4ec745b4ae5ac9a3dd463fa7a3c",
          "label":"",
          "type":"treeNodeObject",
          "styleType":"treeNodeObject",
          "visible":true,
          "style":{
            "location":{
              "x":187,
              "y":350},
            "size":{
              "width":113,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"763a174b592148d68b95ecfbeb9def86",
              "label":"",
              "type":"treeNodeObject",
              "styleType":"treeNodeObject",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "size":{
                  "width":80,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c628c099c4244f1ab1a3d05e26cf3b6f",
                  "label":"",
                  "isContained":true,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a5b722ef90dc4ce8b4e0b577583ba403",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0000FF,
                          "opacity":1},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1325e3e468e943c2917d9a9a847b470c",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":20,
                      "y":20},
                    "size":{
                      "width":93,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d9bc8b77ea694929ac54f999d25c0787",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0000FF,
                          "opacity":1},
                        "location":{
                          "x":20,
                          "y":20},
                        "size":{
                          "width":93,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"8afd6317514946ba92ae17fd1dccf676",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF0000FF,
                              "opacity":1},
                            "location":{
                              "x":20,
                              "y":20},
                            "size":{
                              "width":93,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 t_Machine",
                              "target":{
                                "targetType":"page",
                                "url":"t_machine.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "buttonShapeId":"d9bc8b77ea694929ac54f999d25c0787"},
{
                  "id":"35fecc9c64994378ad206dd03859acfe",
                  "label":"",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "selected":{
}},
                    "location":{
                      "x":6,
                      "y":6},
                    "size":{
                      "width":9,
                      "height":9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6c7526504208446bb332f061a53f7c4f",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
}},
                        "location":{
                          "x":6,
                          "y":6},
                        "size":{
                          "width":9,
                          "height":9}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/guanzhu/u22.png",
                    "selected~":"images/guanzhu/u22_selected.png"}},
{
                  "id":"638c3ac6ccec4b4684bdb0e19faa4a44",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":20,
                      "y":40},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"88d0b03089114940b4492f234475f9d5",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0000FF,
                          "opacity":1},
                        "location":{
                          "x":20,
                          "y":40},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"84ee2a03d3d04df796aa5f002aa91fd1",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF0000FF,
                              "opacity":1},
                            "location":{
                              "x":20,
                              "y":40},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 t_MyLive",
                              "target":{
                                "targetType":"page",
                                "url":"t_mylive.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "buttonShapeId":"88d0b03089114940b4492f234475f9d5"},
{
                  "id":"ab8999b943684d5890b699299b59f6cf",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":20,
                      "y":60},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ad33f6b60a9b485aaa35c736fbc32566",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0000FF,
                          "opacity":1},
                        "location":{
                          "x":20,
                          "y":60},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"e54ea18416f54dffa80506368bce8dbe",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF0000FF,
                              "opacity":1},
                            "location":{
                              "x":20,
                              "y":60},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 t_MyVod",
                              "target":{
                                "targetType":"page",
                                "url":"t_myvod.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "buttonShapeId":"ad33f6b60a9b485aaa35c736fbc32566"},
{
                  "id":"8cacab80fb9a4c3c9faf3f4a1028612b",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":20,
                      "y":80},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"600bd36c76ba413b9b8c7b4ae9a2747a",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0000FF,
                          "opacity":1},
                        "location":{
                          "x":20,
                          "y":80},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"b6740c9ff7d3497b8ecc26cc46f45f98",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF0000FF,
                              "opacity":1},
                            "location":{
                              "x":20,
                              "y":80},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 t_QuestionMgr",
                              "target":{
                                "targetType":"page",
                                "url":"t_questionmgr.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "buttonShapeId":"600bd36c76ba413b9b8c7b4ae9a2747a"},
{
                  "id":"aedb2af6ca6d480899afdc8b84f626c9",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":20,
                      "y":100},
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a4281d11c5864d2cb8789fa2f9391596",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0000FF,
                          "opacity":1},
                        "location":{
                          "x":20,
                          "y":100},
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"b1c542e6c63549b994d74842e9966dbd",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF0000FF,
                              "opacity":1},
                            "location":{
                              "x":20,
                              "y":100},
                            "size":{
                              "width":80,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 t_TestMgr",
                              "target":{
                                "targetType":"page",
                                "url":"t_testmgr.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "buttonShapeId":"a4281d11c5864d2cb8789fa2f9391596"}],
              "buttonShapeId":"c628c099c4244f1ab1a3d05e26cf3b6f"}]},
{
          "id":"00dd9e0abf5143e9b40af5f4b1025ec4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":148,
              "y":302},
            "size":{
              "width":22,
              "height":248}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ec1a9cb088d4efd9c1a9ee3f37d80ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":148,
                  "y":302},
                "size":{
                  "width":22,
                  "height":248}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7c51d075c84e468985d5b5c516d91cd0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1033,
              "y":224},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eadb0c21b72c409c935175e667d5031c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1033,
                  "y":224},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f6e1efdc83e944a8b4360697f6c972d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1102,
              "y":224},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"beb15c04f4cc42b5b7ce613988f0aed1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1102,
                  "y":224},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"31ea63375f9e47fd8d173c8f0841eb84",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":282},
            "size":{
              "width":57,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/guanzhu/u62_line.png"}},
{
          "id":"2cd1364150de4da494f2b05d2b216158",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":224},
            "size":{
              "width":903,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/guanzhu/u63_line.png"}},
{
          "id":"b20583d5627f42ec8279fe155a866e89",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":148,
              "y":224},
            "size":{
              "width":10,
              "height":68}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/guanzhu/u64_line.png"}},
{
          "id":"d2b1a0e8eef94852bf41d6dd76f9cd17",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":840},
            "size":{
              "width":1030,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ead582d9dfa4415984f18aec94c042e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":840},
                "size":{
                  "width":1030,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u185.png"}},
{
          "id":"360f64dd920f43f9a05fa1be376ac556",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":260},
            "size":{
              "width":819,
              "height":550}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ee586a1d21347bbaecb82c48144effb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":350,
                  "y":260},
                "size":{
                  "width":819,
                  "height":550}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/jiaoyi/u67.png"}},
{
          "id":"24146dcf4862444eb6be39a5ae1b520b",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":197,
              "y":480},
            "size":{
              "width":100,
              "height":154}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4a9331e3d7449f9b8efa5ab5ca9c9a1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":34},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ec0aaabff8ca4e5aa0807116a5c5bb01",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":34},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "interactionMap":{
                "onClick":{
                  "description":"OnClick",
                  "cases":[{
                      "description":"用例 1",
                      "isNewIfGroup":false,
                      "actions":[{
                          "action":"linkWindow",
                          "description":"在 当前窗口 打开 UserInfo",
                          "target":{
                            "targetType":"page",
                            "url":"userinfo.html",
                            "includeVariables":true},
                          "linkType":"current"}]}]}},
              "tabbable":true,
              "images":{
                "normal~":"images/guanzhu/u72.png"}},
{
              "id":"7deb03be29794b5db6fb3d45cc8fb8c4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":64},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0a6ed0d5ad144848a0586ff622a7a6f2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":64},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "interactionMap":{
                "onClick":{
                  "description":"OnClick",
                  "cases":[{
                      "description":"用例 1",
                      "isNewIfGroup":false,
                      "actions":[{
                          "action":"linkWindow",
                          "description":"在 当前窗口 打开 ChangePwd",
                          "target":{
                            "targetType":"page",
                            "url":"changepwd.html",
                            "includeVariables":true},
                          "linkType":"current"}]}]}},
              "tabbable":true,
              "images":{
                "normal~":"images/guanzhu/u72.png"}},
{
              "id":"0da0a14c3cc647fe8295f6d2085b85b3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":94},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2f658472fa954fd1ab2e5db7521cd964",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":94},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "interactionMap":{
                "onClick":{
                  "description":"OnClick",
                  "cases":[{
                      "description":"用例 1",
                      "isNewIfGroup":false,
                      "actions":[{
                          "action":"linkWindow",
                          "description":"在 当前窗口 打开 Money",
                          "target":{
                            "targetType":"page",
                            "url":"money.html",
                            "includeVariables":true},
                          "linkType":"current"}]}]}},
              "tabbable":true,
              "images":{
                "normal~":"images/guanzhu/u72.png"}},
{
              "id":"aca88925112d4e52846d5d6a77408a2e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":124},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0d1a8cd873e544d39e038740b89a9bd7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":124},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "interactionMap":{
                "onClick":{
                  "description":"OnClick",
                  "cases":[{
                      "description":"用例 1",
                      "isNewIfGroup":false,
                      "actions":[{
                          "action":"linkWindow",
                          "description":"在 当前窗口 打开 Jiaoyi",
                          "target":{
                            "targetType":"page",
                            "url":"jiaoyi.html",
                            "includeVariables":true},
                          "linkType":"current"}]}]}},
              "tabbable":true,
              "images":{
                "normal~":"images/guanzhu/u78.png"}},
{
              "id":"2a5fd514512f4491835befda59005975",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "size":{
                  "width":100,
                  "height":34}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b28731e289284c5ab0f116814cc9f3a8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1},
                    "size":{
                      "width":100,
                      "height":34}},
                  "adaptiveStyles":{
}}],
              "interactionMap":{
                "onClick":{
                  "description":"OnClick",
                  "cases":[{
                      "description":"用例 1",
                      "isNewIfGroup":false,
                      "actions":[{
                          "action":"linkWindow",
                          "description":"在 当前窗口 打开 Guanzhu",
                          "target":{
                            "targetType":"page",
                            "url":"guanzhu.html",
                            "includeVariables":true},
                          "linkType":"current"}]}]}},
              "tabbable":true,
              "images":{
                "normal~":"images/guanzhu/u70.png"}}]},
{
          "id":"4317bc2f557146e0afbaf2405abcdbd4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":152},
            "size":{
              "width":1030,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"880642caaf954997b2626c8a7c4c120e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":152},
                "size":{
                  "width":1030,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u12.png"}},
{
          "id":"172f54276bd84fd48598dfe7b080a28b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":200,
              "y":164},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f634f87b2d8429f84839ec740036209",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":200,
                  "y":164},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a9d49a75fb6486aa47bf211e1320888",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":253,
              "y":164},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca0e415f194643878a5ca81d974e1152",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":253,
                  "y":164},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 LiveList",
                      "target":{
                        "targetType":"page",
                        "url":"livelist.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bb8b3cb1e0bd4f86b60955693c5bc326",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":320,
              "y":164},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f641679630e4ea5b75081b0acff7abc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":320,
                  "y":164},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 VodList",
                      "target":{
                        "targetType":"page",
                        "url":"vodlist.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b5c59360a8634a558571c537e80058bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":390,
              "y":164},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"383bbe19add7461a9589d148c9395a52",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":390,
                  "y":164},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 SchoolList",
                      "target":{
                        "targetType":"page",
                        "url":"schoollist.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"54635e1513a349f3bd52ec19a5e0f782",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":453,
              "y":164},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11f7c8d2f39245a09c79d8e91a6a22ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":453,
                  "y":164},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 TeacherList",
                      "target":{
                        "targetType":"page",
                        "url":"teacherlist.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "0e624873977b4b9abc1109455bb4437f":{
      "scriptId":"u0"},
    "790335e4598e49eb8183519559718872":{
      "scriptId":"u1"},
    "43ef8e9d3c35411fb326472fe92edbfd":{
      "scriptId":"u2"},
    "22d984a068ba46158aedd4c962746cb0":{
      "scriptId":"u3"},
    "ca15cb5eca094484adee925e8b434a77":{
      "scriptId":"u4"},
    "afcc510127f9444fad6e19b66b004e9a":{
      "scriptId":"u5"},
    "0b13057085134ac6a4eb019b3b24fc48":{
      "scriptId":"u6"},
    "62b53333bcc44bf69cce7b9327fa9c9e":{
      "scriptId":"u7"},
    "46db73ebc63c4c778ffd4be18a6f9135":{
      "scriptId":"u8"},
    "c1e6205ff74b43f68b39ba3faaa5b7c8":{
      "scriptId":"u9"},
    "fa2c937e3fc3407c91393d42db7a7ac3":{
      "scriptId":"u10"},
    "2b56fa6d29974c30a7e8743c2f6be00e":{
      "scriptId":"u11"},
    "c31e70d21c9249178fbe74e736db54f5":{
      "scriptId":"u12"},
    "7531af5d4730446a94a7f2773b29d8f7":{
      "scriptId":"u13"},
    "59b08ce094ac4bcaa9143b507599e19d":{
      "scriptId":"u14"},
    "c3715b84387a44a5ad48378cd4c77a91":{
      "scriptId":"u15"},
    "85d5f3b11ad6453089a4712c59e5c9a0":{
      "scriptId":"u16"},
    "ea57be9fc3c643519c7686a118a92ff2":{
      "scriptId":"u17"},
    "d839a2471f324ed69c5bf7839f411725":{
      "scriptId":"u18"},
    "9868aa24ef6b4fe88a6775066b8fa94c":{
      "scriptId":"u19"},
    "cdd14ef9df2b4b7e988a6bfcfa4e6e79":{
      "scriptId":"u20"},
    "48006ce5bf2f4114b484daefc220153e":{
      "scriptId":"u21"},
    "766c6b257c274c37b2e121a5e1e40a3e":{
      "scriptId":"u22"},
    "3df13c31dae644f8907006b59ffc330e":{
      "scriptId":"u23"},
    "39cee26f22ad43a3bfc38fffe0c960b2":{
      "scriptId":"u24"},
    "0538c1f49d49459f8b4711585eace9ba":{
      "scriptId":"u25"},
    "ed83429f52184887bf8b9a7daee65c7e":{
      "scriptId":"u26"},
    "d9b6526c50444e438cd1c89ad2aedabb":{
      "scriptId":"u27"},
    "8eb37fb0febe4211867505b3dbe18b4b":{
      "scriptId":"u28"},
    "cf40050496544fa69e4e0259893ddef8":{
      "scriptId":"u29"},
    "05bfff0adddb47dc8d2c37d12c7fa49e":{
      "scriptId":"u30"},
    "9cc0d9a1d53c4b4a83b6346a29eb87d7":{
      "scriptId":"u31"},
    "75b5da255b484d8b9f52053e27f3f88e":{
      "scriptId":"u32"},
    "e06d8987eac84841b8fe70a0f5ce8a43":{
      "scriptId":"u33"},
    "bfb76c3960d54a67ac8e7ecb8e6e5ba7":{
      "scriptId":"u34"},
    "8787b4ec745b4ae5ac9a3dd463fa7a3c":{
      "scriptId":"u35"},
    "763a174b592148d68b95ecfbeb9def86":{
      "scriptId":"u36"},
    "35fecc9c64994378ad206dd03859acfe":{
      "scriptId":"u37"},
    "6c7526504208446bb332f061a53f7c4f":{
      "scriptId":"u38"},
    "c628c099c4244f1ab1a3d05e26cf3b6f":{
      "scriptId":"u39"},
    "a5b722ef90dc4ce8b4e0b577583ba403":{
      "scriptId":"u40"},
    "1325e3e468e943c2917d9a9a847b470c":{
      "scriptId":"u41"},
    "d9bc8b77ea694929ac54f999d25c0787":{
      "scriptId":"u42"},
    "8afd6317514946ba92ae17fd1dccf676":{
      "scriptId":"u43"},
    "638c3ac6ccec4b4684bdb0e19faa4a44":{
      "scriptId":"u44"},
    "88d0b03089114940b4492f234475f9d5":{
      "scriptId":"u45"},
    "84ee2a03d3d04df796aa5f002aa91fd1":{
      "scriptId":"u46"},
    "ab8999b943684d5890b699299b59f6cf":{
      "scriptId":"u47"},
    "ad33f6b60a9b485aaa35c736fbc32566":{
      "scriptId":"u48"},
    "e54ea18416f54dffa80506368bce8dbe":{
      "scriptId":"u49"},
    "8cacab80fb9a4c3c9faf3f4a1028612b":{
      "scriptId":"u50"},
    "600bd36c76ba413b9b8c7b4ae9a2747a":{
      "scriptId":"u51"},
    "b6740c9ff7d3497b8ecc26cc46f45f98":{
      "scriptId":"u52"},
    "aedb2af6ca6d480899afdc8b84f626c9":{
      "scriptId":"u53"},
    "a4281d11c5864d2cb8789fa2f9391596":{
      "scriptId":"u54"},
    "b1c542e6c63549b994d74842e9966dbd":{
      "scriptId":"u55"},
    "00dd9e0abf5143e9b40af5f4b1025ec4":{
      "scriptId":"u56"},
    "3ec1a9cb088d4efd9c1a9ee3f37d80ae":{
      "scriptId":"u57"},
    "7c51d075c84e468985d5b5c516d91cd0":{
      "scriptId":"u58"},
    "eadb0c21b72c409c935175e667d5031c":{
      "scriptId":"u59"},
    "f6e1efdc83e944a8b4360697f6c972d9":{
      "scriptId":"u60"},
    "beb15c04f4cc42b5b7ce613988f0aed1":{
      "scriptId":"u61"},
    "31ea63375f9e47fd8d173c8f0841eb84":{
      "scriptId":"u62"},
    "2cd1364150de4da494f2b05d2b216158":{
      "scriptId":"u63"},
    "b20583d5627f42ec8279fe155a866e89":{
      "scriptId":"u64"},
    "d2b1a0e8eef94852bf41d6dd76f9cd17":{
      "scriptId":"u65"},
    "0ead582d9dfa4415984f18aec94c042e":{
      "scriptId":"u66"},
    "360f64dd920f43f9a05fa1be376ac556":{
      "scriptId":"u67"},
    "3ee586a1d21347bbaecb82c48144effb":{
      "scriptId":"u68"},
    "24146dcf4862444eb6be39a5ae1b520b":{
      "scriptId":"u69"},
    "2a5fd514512f4491835befda59005975":{
      "scriptId":"u70"},
    "b28731e289284c5ab0f116814cc9f3a8":{
      "scriptId":"u71"},
    "f4a9331e3d7449f9b8efa5ab5ca9c9a1":{
      "scriptId":"u72"},
    "ec0aaabff8ca4e5aa0807116a5c5bb01":{
      "scriptId":"u73"},
    "7deb03be29794b5db6fb3d45cc8fb8c4":{
      "scriptId":"u74"},
    "0a6ed0d5ad144848a0586ff622a7a6f2":{
      "scriptId":"u75"},
    "0da0a14c3cc647fe8295f6d2085b85b3":{
      "scriptId":"u76"},
    "2f658472fa954fd1ab2e5db7521cd964":{
      "scriptId":"u77"},
    "aca88925112d4e52846d5d6a77408a2e":{
      "scriptId":"u78"},
    "0d1a8cd873e544d39e038740b89a9bd7":{
      "scriptId":"u79"},
    "4317bc2f557146e0afbaf2405abcdbd4":{
      "scriptId":"u80"},
    "880642caaf954997b2626c8a7c4c120e":{
      "scriptId":"u81"},
    "172f54276bd84fd48598dfe7b080a28b":{
      "scriptId":"u82"},
    "9f634f87b2d8429f84839ec740036209":{
      "scriptId":"u83"},
    "6a9d49a75fb6486aa47bf211e1320888":{
      "scriptId":"u84"},
    "ca0e415f194643878a5ca81d974e1152":{
      "scriptId":"u85"},
    "bb8b3cb1e0bd4f86b60955693c5bc326":{
      "scriptId":"u86"},
    "2f641679630e4ea5b75081b0acff7abc":{
      "scriptId":"u87"},
    "b5c59360a8634a558571c537e80058bc":{
      "scriptId":"u88"},
    "383bbe19add7461a9589d148c9395a52":{
      "scriptId":"u89"},
    "54635e1513a349f3bd52ec19a5e0f782":{
      "scriptId":"u90"},
    "11f7c8d2f39245a09c79d8e91a6a22ac":{
      "scriptId":"u91"}}});